<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>论文正文</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="论文正文_files/libs/clipboard/clipboard.min.js"></script>
<script src="论文正文_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="论文正文_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="论文正文_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="论文正文_files/libs/quarto-html/popper.min.js"></script>
<script src="论文正文_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="论文正文_files/libs/quarto-html/anchor.min.js"></script>
<link href="论文正文_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="论文正文_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="论文正文_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="论文正文_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="论文正文_files/libs/bootstrap/bootstrap-a74871fe4945b66d259aafc266475145.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#第一章-绪论" id="toc-第一章-绪论" class="nav-link active" data-scroll-target="#第一章-绪论">第一章 绪论</a>
  <ul class="collapse">
  <li><a href="#研究背景" id="toc-研究背景" class="nav-link" data-scroll-target="#研究背景">1.1 研究背景</a></li>
  <li><a href="#研究目的与意义" id="toc-研究目的与意义" class="nav-link" data-scroll-target="#研究目的与意义">1.2 研究目的与意义</a>
  <ul class="collapse">
  <li><a href="#理论意义" id="toc-理论意义" class="nav-link" data-scroll-target="#理论意义">1.2.1 理论意义</a></li>
  <li><a href="#实践意义" id="toc-实践意义" class="nav-link" data-scroll-target="#实践意义">1.2.2 实践意义</a></li>
  </ul></li>
  <li><a href="#国内外研究现状与文献综述" id="toc-国内外研究现状与文献综述" class="nav-link" data-scroll-target="#国内外研究现状与文献综述">1.3 国内外研究现状与文献综述</a>
  <ul class="collapse">
  <li><a href="#足球时空数据与热图可视化研究" id="toc-足球时空数据与热图可视化研究" class="nav-link" data-scroll-target="#足球时空数据与热图可视化研究">1.3.1 足球时空数据与热图可视化研究</a></li>
  <li><a href="#足球动作战术价值评价研究" id="toc-足球动作战术价值评价研究" class="nav-link" data-scroll-target="#足球动作战术价值评价研究">1.3.2 足球动作战术价值评价研究</a></li>
  <li><a href="#地统计学在体育空间分析中的应用" id="toc-地统计学在体育空间分析中的应用" class="nav-link" data-scroll-target="#地统计学在体育空间分析中的应用">1.3.3 地统计学在体育空间分析中的应用</a></li>
  </ul></li>
  <li><a href="#研究问题" id="toc-研究问题" class="nav-link" data-scroll-target="#研究问题">1.4 研究问题</a></li>
  <li><a href="#研究内容与框架" id="toc-研究内容与框架" class="nav-link" data-scroll-target="#研究内容与框架">1.5 研究内容与框架</a></li>
  <li><a href="#研究创新点" id="toc-研究创新点" class="nav-link" data-scroll-target="#研究创新点">1.6 研究创新点</a></li>
  </ul></li>
  <li><a href="#第二章-数据介绍与数据清洗" id="toc-第二章-数据介绍与数据清洗" class="nav-link" data-scroll-target="#第二章-数据介绍与数据清洗">第二章 数据介绍与数据清洗</a>
  <ul class="collapse">
  <li><a href="#数据来源与研究样本选择" id="toc-数据来源与研究样本选择" class="nav-link" data-scroll-target="#数据来源与研究样本选择">2.1 数据来源与研究样本选择</a></li>
  <li><a href="#数据采集与空间坐标系的重构" id="toc-数据采集与空间坐标系的重构" class="nav-link" data-scroll-target="#数据采集与空间坐标系的重构">2.2 数据采集与空间坐标系的重构</a></li>
  <li><a href="#数据清洗与降噪机制" id="toc-数据清洗与降噪机制" class="nav-link" data-scroll-target="#数据清洗与降噪机制">2.3 数据清洗与降噪机制</a></li>
  <li><a href="#核心变量筛选与数据字典构建" id="toc-核心变量筛选与数据字典构建" class="nav-link" data-scroll-target="#核心变量筛选与数据字典构建">2.4 核心变量筛选与数据字典构建</a></li>
  <li><a href="#数据规模与样本清洗结果" id="toc-数据规模与样本清洗结果" class="nav-link" data-scroll-target="#数据规模与样本清洗结果">2.5 数据规模与样本清洗结果</a></li>
  </ul></li>
  <li><a href="#第三章-概念界定与理论模型介绍" id="toc-第三章-概念界定与理论模型介绍" class="nav-link" data-scroll-target="#第三章-概念界定与理论模型介绍">第三章 概念界定与理论模型介绍</a>
  <ul class="collapse">
  <li><a href="#传统空间分布估计模型" id="toc-传统空间分布估计模型" class="nav-link" data-scroll-target="#传统空间分布估计模型">3.1 传统空间分布估计模型</a>
  <ul class="collapse">
  <li><a href="#核密度估计法-kernel-density-estimation-kde" id="toc-核密度估计法-kernel-density-estimation-kde" class="nav-link" data-scroll-target="#核密度估计法-kernel-density-estimation-kde">3.1.1 核密度估计法 (Kernel Density Estimation, KDE)</a></li>
  </ul></li>
  <li><a href="#空间统计学与克里金插值模型" id="toc-空间统计学与克里金插值模型" class="nav-link" data-scroll-target="#空间统计学与克里金插值模型">3.2 空间统计学与克里金插值模型</a>
  <ul class="collapse">
  <li><a href="#空间自相关与战术溢出效应" id="toc-空间自相关与战术溢出效应" class="nav-link" data-scroll-target="#空间自相关与战术溢出效应">3.2.1 空间自相关与战术溢出效应</a></li>
  <li><a href="#变异函数" id="toc-变异函数" class="nav-link" data-scroll-target="#变异函数">3.2.2 变异函数</a></li>
  <li><a href="#普通克里金插值法及其数学推导" id="toc-普通克里金插值法及其数学推导" class="nav-link" data-scroll-target="#普通克里金插值法及其数学推导">3.2.3 普通克里金插值法及其数学推导</a></li>
  </ul></li>
  <li><a href="#足球球权战术价值评价体系z-模型的构建" id="toc-足球球权战术价值评价体系z-模型的构建" class="nav-link" data-scroll-target="#足球球权战术价值评价体系z-模型的构建">3.3 足球球权战术价值评价体系（Z 模型）的构建</a>
  <ul class="collapse">
  <li><a href="#模型特征选择的理论与数据依据" id="toc-模型特征选择的理论与数据依据" class="nav-link" data-scroll-target="#模型特征选择的理论与数据依据">3.3.1 模型特征选择的理论与数据依据</a></li>
  <li><a href="#z-模型的多维特征乘法构建" id="toc-z-模型的多维特征乘法构建" class="nav-link" data-scroll-target="#z-模型的多维特征乘法构建">3.3.2 Z 模型的多维特征乘法构建</a></li>
  <li><a href="#模型参数设定与稳健性检验" id="toc-模型参数设定与稳健性检验" class="nav-link" data-scroll-target="#模型参数设定与稳健性检验">3.3.3 模型参数设定与稳健性检验</a></li>
  <li><a href="#多维主观参数敏感性分析结果-oat" id="toc-多维主观参数敏感性分析结果-oat" class="nav-link" data-scroll-target="#多维主观参数敏感性分析结果-oat">多维主观参数敏感性分析结果 (OAT)</a></li>
  <li><a href="#模型算法的程序实现" id="toc-模型算法的程序实现" class="nav-link" data-scroll-target="#模型算法的程序实现">3.3.4 模型算法的程序实现</a></li>
  </ul></li>
  <li><a href="#空间变异特性的提取与参数拟合" id="toc-空间变异特性的提取与参数拟合" class="nav-link" data-scroll-target="#空间变异特性的提取与参数拟合">3.4 空间变异特性的提取与参数拟合</a>
  <ul class="collapse">
  <li><a href="#空间搜索距离与邻域参数的设定" id="toc-空间搜索距离与邻域参数的设定" class="nav-link" data-scroll-target="#空间搜索距离与邻域参数的设定">3.4.1 空间搜索距离与邻域参数的设定</a></li>
  <li><a href="#空间搜索距离与邻域参数的设定-1" id="toc-空间搜索距离与邻域参数的设定-1" class="nav-link" data-scroll-target="#空间搜索距离与邻域参数的设定-1">3.4.1 空间搜索距离与邻域参数的设定</a></li>
  <li><a href="#变异函数的提取与理论拟合" id="toc-变异函数的提取与理论拟合" class="nav-link" data-scroll-target="#变异函数的提取与理论拟合">3.4.2 变异函数的提取与理论拟合</a></li>
  </ul></li>
  <li><a href="#模型预测精度评估5折交叉验证5-fold-cv" id="toc-模型预测精度评估5折交叉验证5-fold-cv" class="nav-link" data-scroll-target="#模型预测精度评估5折交叉验证5-fold-cv">3.5 模型预测精度评估：5折交叉验证（5-fold CV）</a></li>
  <li><a href="#空间插值算法选型普通克里金与泛克里金的对比论证" id="toc-空间插值算法选型普通克里金与泛克里金的对比论证" class="nav-link" data-scroll-target="#空间插值算法选型普通克里金与泛克里金的对比论证">3.6 空间插值算法选型：普通克里金与泛克里金的对比论证</a>
  <ul class="collapse">
  <li><a href="#预测误差量化对比" id="toc-预测误差量化对比" class="nav-link" data-scroll-target="#预测误差量化对比">3.6.1 预测误差量化对比</a></li>
  <li><a href="#价值场视觉重构对比" id="toc-价值场视觉重构对比" class="nav-link" data-scroll-target="#价值场视觉重构对比">3.6.2 价值场视觉重构对比</a></li>
  <li><a href="#选型结论奥卡姆剃刀与-z-模型的自洽性反证" id="toc-选型结论奥卡姆剃刀与-z-模型的自洽性反证" class="nav-link" data-scroll-target="#选型结论奥卡姆剃刀与-z-模型的自洽性反证">3.6.3 选型结论：奥卡姆剃刀与 <span class="math inline">\(Z\)</span> 模型的自洽性反证</a></li>
  </ul></li>
  <li><a href="#空间可视化范式跨越传统-kde-与克里金价值场的实证对比" id="toc-空间可视化范式跨越传统-kde-与克里金价值场的实证对比" class="nav-link" data-scroll-target="#空间可视化范式跨越传统-kde-与克里金价值场的实证对比">3.7 空间可视化范式跨越：传统 KDE 与克里金价值场的实证对比</a>
  <ul class="collapse">
  <li><a href="#宏观全景视角全联盟价值基准场的剥离效应" id="toc-宏观全景视角全联盟价值基准场的剥离效应" class="nav-link" data-scroll-target="#宏观全景视角全联盟价值基准场的剥离效应">3.7.1 宏观全景视角：全联盟价值基准场的剥离效应</a></li>
  <li><a href="#微观极限视角单场稀疏样本下的鲁棒性检验" id="toc-微观极限视角单场稀疏样本下的鲁棒性检验" class="nav-link" data-scroll-target="#微观极限视角单场稀疏样本下的鲁棒性检验">3.7.2 微观极限视角：单场稀疏样本下的鲁棒性检验</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#参考文献" id="toc-参考文献" class="nav-link" data-scroll-target="#参考文献">参考文献</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">论文正文</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="第一章-绪论" class="level1">
<h1>第一章 绪论</h1>
<section id="研究背景" class="level2">
<h2 class="anchored" data-anchor-id="研究背景">1.1 研究背景</h2>
<p>在现代足球战术体系的演进中，空间控制力的量化已成为职业球队评估比赛表现、制定战术决策的核心指标。随着光学追踪技术与事件记录系统（Event Data）的普及，足球数据分析正经历从传统的“结果频次统计”（如控球率、射门数）向高维度的“时空过程分析”跨越。在这一背景下，如何直观且科学地呈现球员或球队在球场上的活动范围与威胁区域，成为了体育工程与数据分析领域亟待突破的热点课题。</p>
<p>目前，工业界生成足球热点图的主流非参数化方法为核密度估计法（Kernel Density Estimation, KDE）。该方法通过叠加核函数，能够以极低的时耗生成平滑的概率密度表面。然而，随着现代足球战术分析深度的增加，传统非参数化空间制图工具的系统性瓶颈逐渐显现，主要集中于以下三个痛点： 1. <strong>“频率”与“质量”的割裂</strong>：KDE 本质上是一种“计数”逻辑，容易导致高频无效触球（如后场倒脚）在视觉上掩盖了低频高危动作（如致命直塞）的战术价值。 2. <strong>空间联动性的忽视</strong>：足球场是一个强相关的有机体，但现有常规方法假设触球事件相互独立，忽略了战术动作在空间上的“溢出效应”与自相关趋势。 3. <strong>统计推断能力的缺失</strong>：传统热图无法提供反映预测置信度的误差分布，使得基于热图的临场决策缺乏严密的统计学安全边界。</p>
<p>针对上述行业痛点，足球数据分析领域亟需引入一种全新的空间建模范式，以打破传统“频率统计”的桎梏，实现向“空间价值评估”与“严密统计推断”的跨越。</p>
</section>
<section id="研究目的与意义" class="level2">
<h2 class="anchored" data-anchor-id="研究目的与意义">1.2 研究目的与意义</h2>
<p>本研究旨在引入地统计学中的克里金（Kriging）空间插值算法，并结合德甲联赛的真实事件数据，构建一套融合动态战术权重的“球权空间价值推演模型”。其核心意义体现在以下两个维度：</p>
<section id="理论意义" class="level3">
<h3 class="anchored" data-anchor-id="理论意义">1.2.1 理论意义</h3>
<p>本研究推动了足球空间分析从“描述性可视化”向“参数化统计推断”的实质性跨越。 首先，本研究创新性地将地质学中的“空间自相关性（Spatial Autocorrelation）”引入足球场，利用变异函数（Variogram）定量表征了足球战术事件的地理依赖特征，为足球地理信息系统（GIS）分析确立了更严密的参数化底层逻辑。其次，研究利用克里金法“最佳线性无偏估计（BLUE）”的特性，填补了体育空间分析在“不确定性量化”方面的理论空白。模型所输出的预测方差（Kriging Variance），为评估体育空间数据的异质性与统计学信度提供了全新的数理依据。</p>
</section>
<section id="实践意义" class="level3">
<h3 class="anchored" data-anchor-id="实践意义">1.2.2 实践意义</h3>
<p>在实战应用层面，本研究为职业足球的精准战术复盘与资产评估提供了极具决策价值的量化导航。 一方面，模型生成的“误差热图”具有极强的实战预警价值，能够直观标注出因样本稀疏而导致预测不可信的“情报盲区”，有效降低教练组因过度解读数据噪音而产生的战术布阵失误。另一方面，本研究建立的基于“空间质量”而非“空间频率”的复合评价体系（即 <span class="math inline">\(Z\)</span> 模型），能更客观地量化那些在低频区域做出关键战术贡献的球员（如拖后组织核心、空间穿插型前锋）。这不仅丰富了球队日常的战术诊断工具箱，更为职业俱乐部的引援定价、青训选拔以及针对性防守策略制定提供了无可辩驳的量化标尺。</p>
</section>
</section>
<section id="国内外研究现状与文献综述" class="level2">
<h2 class="anchored" data-anchor-id="国内外研究现状与文献综述">1.3 国内外研究现状与文献综述</h2>
<section id="足球时空数据与热图可视化研究" class="level3">
<h3 class="anchored" data-anchor-id="足球时空数据与热图可视化研究">1.3.1 足球时空数据与热图可视化研究</h3>
<p>足球大数据研究的基石在于高质量时空数据集的构建。Pappalardo 等（2019）引入了大规模公开事件数据集（Event Data），使得分析维度从宏观统计深入到微观坐标。在此基础上，Link 等（2016）率先利用核密度估计法（KDE）构建了职业足球的实时球权区域分布图。</p>
<p><strong>现有研究不足：</strong> 传统 KDE 热图本质上是“基于点位密度的概率测算”，极易受高频无效数据（如后场安全倒脚）的视觉霸权干扰。其仅能反映球权发生的“频率”，却完全剥离了动作背后的战术“质量”。</p>
</section>
<section id="足球动作战术价值评价研究" class="level3">
<h3 class="anchored" data-anchor-id="足球动作战术价值评价研究">1.3.2 足球动作战术价值评价研究</h3>
<p>为突破“唯频次论”，学术界开始探索动作价值的量化。从早期的预期进球模型（xG），到 Decroos 等（2019）提出的 VAEP 框架，研究者成功将足球比赛视为马尔可夫链状态转移过程，量化了传球、盘带等非射门动作对最终进球的边际贡献。</p>
<p><strong>现有研究不足：</strong> 现有的价值评价模型（如 VAEP）大多侧重于对“离散动作”或“单个球员”的打分，缺乏将这些价值点映射为“连续空间表面”的方法，难以直观呈现球队整体的空间控制力与战术倾斜。</p>
</section>
<section id="地统计学在体育空间分析中的应用" class="level3">
<h3 class="anchored" data-anchor-id="地统计学在体育空间分析中的应用">1.3.3 地统计学在体育空间分析中的应用</h3>
<p>为克服 KDE 缺乏统计推断能力的短板，Kotzbek 与 Kainz（2015）探讨了利用克里金插值处理足球追踪数据的可能性。Yue 等（2014）证实了足球场上事件分布存在显著的距离衰减与空间溢出效应，为克里金法的应用提供了合法性依据。</p>
<p><strong>现有研究不足：</strong> 目前地统计学在体育领域的应用多停留在探索性阶段，既缺乏将复杂战术规则（如防守压迫、传球高度）内化为空间权重的复合评价体系，也鲜有研究利用克里金方差来输出战术决策的“数据置信度”。本研究正是为填补上述理论与应用空白而展开。</p>
</section>
</section>
<section id="研究问题" class="level2">
<h2 class="anchored" data-anchor-id="研究问题">1.4 研究问题</h2>
<p>基于上述文献评述与研究空白，本研究致力于回答以下三个核心研究问题：</p>
<ul>
<li><p><strong>RQ1：</strong> 德甲球权战术价值在二维球场上是否存在显著的空间自相关性？其有效战术辐射半径如何量化？</p></li>
<li><p><strong>RQ2：</strong> 相较于传统的核密度估计（KDE），引入先验空间结构的克里金方法能否更精准地剥离数据噪音，揭示真实的“高价值战术空间”？</p></li>
<li><p><strong>RQ3：</strong> 在面对单场比赛等稀疏小样本数据时，基于全赛季先验变异函数的克里金插值是否具备更强的推断鲁棒性与决策安全性？</p></li>
</ul>
</section>
<section id="研究内容与框架" class="level2">
<h2 class="anchored" data-anchor-id="研究内容与框架">1.5 研究内容与框架</h2>
<p>本研究打破传统足球分析中依赖核密度估计的局限，深度探讨球权分布的空间结构及其潜在战术价值 。整体研究框架分为以下五个部分：</p>
<ol type="1">
<li><p><strong>理论基础与指标构建</strong>：突破传统空间分析仅关注事件发生位置的局限，本研究首先构建了多维度的“球权战术价值（<span class="math inline">\(Z\)</span>）”指标体系。该体系深度融合了动作基础分、空间向心力权重、防守压迫情境与动作质量等复合变量，赋予每个离散的触球坐标点客观的“价值属性”。其目的在于探索一种能够同时量化球权发生频率与潜在威胁权重的分析框架，实现对足球场空间控制力的精细化评估。</p></li>
<li><p><strong>空间相关性验证与变异函数分析</strong>：研究提取了德甲赛事的球权事件核心坐标，重点通过拟合实验变异函数，对球权分布的空间自相关性进行定量表征。此步骤旨在验证足球比赛中球权事件的空间属性，证明球场上的战术事件并非随机散布，而是存在着显著的空间依赖特征。这不仅是论证克里金模型应用可行性的核心环节，更是后续进行全场连续插值的理论前提。</p></li>
<li><p><strong>克里金插值建模与全景场生成</strong>：基于提取的变异函数先验参数，本研究构建了普通克里金空间模型。利用其“最佳线性无偏估计”的数理特性，将离散的球权事件转化为连续且平滑的“球权价值基准场”。同时，本部分将进行多维度的模型对比与不确定性评估，利用5折交叉验证（5-fold CV）计算绝对误差（RMSE）与预测方差（MSDR）等。并利用克里金方差输出生成反映数据置信度的“误差热图”，从而科学地界定战术分析中的预测盲区。</p></li>
<li><p><strong>宏观战术实证分析</strong>：在基准模型建立后，研究将以特定球队为例，生成单队的战术价值场，并与全联盟基准场进行空间差值计算，生成战术差异残差图。通过对比高、低价值区域的转移趋势，直观识别球队在不同战术体系下空间控制的结构化差异以及在空间创造上面临的机遇与困境。这一宏观分析旨在为职业足球教练组提供具备数学置信度的战术诊断与优化依据。</p></li>
<li><p><strong>微观球员实证分析</strong>：最后，本研究将模型的观测尺度下沉至个人维度，选取具有典型空间特征的代表性球员，生成个人专属的克里金价值热图。重点探讨该模型在评估“空间阅读型”或“低频高危”动作型球员（如拖后组织核心、致命传球手）时的降维打击优势。通过与传统 KDE 频率图的面对面横向对比，纠正传统频率模型带来的视觉霸权与评价偏差，完成对球员真实空间战术贡献的客观重塑。</p></li>
</ol>
</section>
<section id="研究创新点" class="level2">
<h2 class="anchored" data-anchor-id="研究创新点">1.6 研究创新点</h2>
<ol type="1">
<li><strong>方法论创新</strong>：从非参数平滑到参数化统计推断</li>
</ol>
<p>本研究创新性地将地质学领域的克里金法系统引入足球战术分析。通过考虑空间自相关性这一核心变量，模型弥补了传统 KDE 算法在处理离散数据时对空间规律的忽视，提供了具有更强数学解释力的预测表面。</p>
<ol start="2" type="1">
<li><strong>评价维度拓展</strong>：实现“事件频率”与“战术价值”的深度融合</li>
</ol>
<p>突破了现有热图仅展示“球在哪里活动”的表象，本研究自创了多维度的价值加权函数，将球权行为的“质量信息”（如威胁度、受迫状态）转化为空间权重。生成的模型不再是一张活动轨迹图，而是动态的“空间潜在收益图”。</p>
<ol start="3" type="1">
<li><strong>决策安全性创新</strong>：引入数据置信度量化机制</li>
</ol>
<p>利用克里金法输出预测方差的特性，本研究在战术分析中引入了“置信度”与“不确定性”概念。这使得分析师能够清晰识别由样本不足引发的统计伪影，为现代足球的高风险战术决策提供了可量化的安全边界。</p>
</section>
</section>
<section id="第二章-数据介绍与数据清洗" class="level1">
<h1>第二章 数据介绍与数据清洗</h1>
<section id="数据来源与研究样本选择" class="level2">
<h2 class="anchored" data-anchor-id="数据来源与研究样本选择">2.1 数据来源与研究样本选择</h2>
<p>本研究的底层原始数据来源于国际知名的足球数据与分析服务商 StatsBomb 提供的公开开源数据集 (StatsBomb Open Data)。相较于传统仅记录进球、红黄牌等宏观结果的统计数据，StatsBomb 的事件数据 (Event Data) 以其极高的数据颗粒度著称，能够精确捕捉球场上每一次触球的二维坐标、传球高度、防守受迫状态等深度战术细节。</p>
<p><strong>基于 StatsBombR 的数据获取与解析机制：</strong> 在数据的获取与工程解析层面，由于 StatsBomb 的底层原始数据采用高度嵌套的 JSON (JavaScript Object Notation) 格式存储，直接提取空间特征与事件属性存在极大的数据清洗壁垒。为此，本研究引入了由其官方团队开发并维护的 R 语言专用接口包 <code>StatsBombR</code>。该宏包通过底层封装 API 请求逻辑，为数据科学家提供了极为便捷的访问与反序列化通道。在实际操作中，本研究首先调用 <code>FreeCompetitions()</code> 函数请求开源赛事大类目录，继而通过 <code>FreeMatches()</code> 函数锁定特定赛季的场次元数据（Metadata）。最终，依靠核心抓取函数 <code>get.matchFree()</code> 遍历执行数据拉取，成功将原本嵌套冗杂的百万级时空坐标与战术事件向量，自动化解析并初步重塑为 R 语言原生的标准数据框（Data Frame）结构。这一严密的数据获取流，为后续的空间统计建模提供了坚实且纯净的数据底座。</p>
<p><strong>实证样本的战术背景选型：</strong> 在实证样本的选择上，本研究定向调取了 2015-2016 赛季德国足球甲级联赛 (1. Bundesliga) 的全赛季比赛事件记录。选择该赛季作为实证对象具有深刻的战术背景考量：该时期正值佩普·瓜迪奥拉执教拜仁慕尼黑的时期，其所推崇的“Juego de Posición”（位置理学）与极致的空间压迫战术，将现代足球对空间的利用推向了新的高度，联赛的这为本研究中强调“地面控制”与“空间向心效能”的 <span class="math inline">\(Z\)</span> 模型价值建模，提供了最具代表性与分析价值的实证载体。同时，该赛季的数据资料也更为完整，且相较于杯赛以及其他国际赛事，联赛会因为更长的周期而有更具稳定性的结果。</p>
</section>
<section id="数据采集与空间坐标系的重构" class="level2">
<h2 class="anchored" data-anchor-id="数据采集与空间坐标系的重构">2.2 数据采集与空间坐标系的重构</h2>
<p>在数据获取阶段，由于全赛季数据量庞大且 StatsBomb API 存在访问频次限制，本研究构建了自动化的批量抓取与异常处理机制。通过 <code>for</code> 循环遍历全赛季所有场次的基础元数据，并嵌套 <code>tryCatch</code> 异常捕获函数，有效避免了因单场数据缺失或网络波动导致的抓取中断 。为提升运算效率并保障数据完整性，原始事件流被合并后序列化存储为 <code>.rds</code> 格式，大幅降低了内存读取负担与重复请求的时间成本 。</p>
<p>原始的 StatsBomb 事件流数据采用 JSON 格式进行多层级嵌套存储。在此结构下，一个单一的战术事件不仅包含基础时间与实体属性，还深度嵌套了触球点的空间位置数组。这种高度非结构化的数据形态无法直接输入至克里金空间地统计模型中。为此，本研究在预处理的初始阶段调用了 <code>allclean()</code> 函数对原始数据框进行了“扁平化”重塑 。 该操作成功将嵌套的地理位置信息剥离，转化为独立的 <code>location.x</code>（纵向推进坐标）和 <code>location.y</code>（横向位置坐标）字段 。StatsBomb 官方采用 <span class="math inline">\(120 \times 80\)</span> 的标准化二维坐标系，该坐标系在物理尺度上以“码（Yard）”为基准映射单元（<span class="math inline">\(1\)</span> 单位坐标 <span class="math inline">\(\approx 0.914\)</span> 米）。为最大程度保障原始追踪数据的空间拓扑纯度，避免在强行公制换算中引入浮点数计算误差，本研究在后续的空间相关性建模与克里金插值过程中，全流程未进行比例换算，而是严格沿用该“标准坐标单位（Standard Coordinate Unit）”作为距离量纲。后文涉及的所有空间距离参数（如变异函数中的滞后步长、变程等）均在此坐标体系下进行学术解释。</p>
</section>
<section id="数据清洗与降噪机制" class="level2">
<h2 class="anchored" data-anchor-id="数据清洗与降噪机制">2.3 数据清洗与降噪机制</h2>
<p>经过扁平化处理后的全赛季初始数据集（包含百万级行数）规模臃肿，且裹挟了大量维持比赛记录运转但缺乏实际战术空间意义的冗余节点。在界定研究边界时，本文明确以“具有有效二维空间坐标、且与实战球权操作或防守干预直接相关的战术事件”作为基本观测单元。为确保输入模型的要素纯净度，本研究依托 <code>tidyverse</code> 核心生态，制定了严密的四步数据清洗与降噪过滤规则：</p>
<ol type="1">
<li><p><strong>非战术实体事件的剔除与样本确立</strong>： 在标准的比赛数据日志中，存在大量系统运作类标签（如首发名单 <code>Starting XI</code>、半场起止 <code>Half Start/End</code>、战术换人调整 <code>Substitution</code> 等）。此类记录不涉及实体球权转移，亦不包含比赛空间坐标变量。本研究通过 <code>filter()</code> 函数明确剔除了此类无效噪音。经过严格筛选，最终纳入 <span class="math inline">\(Z\)</span> 模型建模的<strong>保留事件清单</strong>主要涵盖以下三大实战类目：</p>
<ul>
<li><strong>绝对控球类</strong>：传球 (<code>Pass</code>)、接球 (<code>Ball Receipt*</code>)、推进带球 (<code>Carry</code>)、盘带突破 (<code>Dribble</code>)、射门 (<code>Shot</code>) 等；</li>
<li><strong>防守干预类</strong>：施压 (<code>Pressure</code>)、对抗 (<code>Duel</code>)、解围 (<code>Clearance</code>)、封堵 (<code>Block</code>)、拦截 (<code>Interception</code>) 等；</li>
<li><strong>权属转换类</strong>：球权恢复 (<code>Ball Recovery</code>)、停球失误/被抢断 (<code>Miscontrol</code> / <code>Dispossessed</code>) 等。 这一清洗步骤从根本上确保了进入空间分析模型的数据点均具备实质性的物理坐标与战术评估价值。</li>
</ul></li>
<li><p><strong>防守压迫状态的逻辑插补</strong>： 引入生态动力学中的“防守约束”是本研究空间价值评估模型的创新点之一。根据 StatsBomb 的标记逻辑，仅当球员在执行技术动作时受到防守方高强度贴防时，<code>under_pressure</code> 字段才会被标记为 <code>TRUE</code>；而在常态无压迫情形下，该字段则遗留为系统缺失值 (NA) 。为消除缺失值对后续数学运算（如 <span class="math inline">\(C_{pressure}\)</span> 系数的标量乘法）的阻断，本研究利用 <code>replace_na()</code> 函数将该列的空白值统一逻辑插补为 <code>FALSE</code> ，完成了对抗环境特征的二元标准化。</p></li>
<li><p><strong>关键战术结果的条件提取</strong>： 为了对特定战术动作进行合理的价值赋分，本研究针对性地保留了包含结果导向的嵌套字段。例如，提取 <code>pass.shot_assist</code> 逻辑值以界定直接促成射门的关键传球 ；提取 <code>dribble.outcome.name</code> 字符串以判定突破过人的成功率 。这些微观结果标签为区分“有效战术执行”与“球权丧失失误”提供了刚性判据。</p></li>
<li><p><strong>时序标准化定型</strong>： 清洗流的最终环节是重构比赛的时间序列。全样本数据严格按照比赛唯一标识符 (<code>match_id</code>)、比赛分钟 (<code>minute</code>) 与比赛秒数 (<code>second</code>) 进行升序重排 (<code>arrange</code>) 。这不仅消除了并发记录引发的乱序隐患，也为还原真实的战术演进路径提供了连贯的时序底座。</p></li>
</ol>
</section>
<section id="核心变量筛选与数据字典构建" class="level2">
<h2 class="anchored" data-anchor-id="核心变量筛选与数据字典构建">2.4 核心变量筛选与数据字典构建</h2>
<p>经过上述降噪过滤，本研究利用 <code>select()</code> 函数从包含数百个维度的全景数据框中，精准提纯了构建“球权战术价值 (<span class="math inline">\(Z\)</span>) 模型”所必需的核心变量组 。为清晰界定各变量在数学建模与战术解析中的实际效用，本研究对提取的特征进行了逻辑归类，并构建了核心变量数据字典。</p>
<p><span class="math inline">\(Z\)</span> 模型核心空间与战术特征数据字典</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">维度归类</th>
<th style="text-align: left;">原始字段名称</th>
<th style="text-align: left;">数据格式</th>
<th style="text-align: left;">物理/战术含义说明</th>
<th style="text-align: left;">数据清洗与提取规则</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>空间坐标基础</strong></td>
<td style="text-align: left;"><code>location.x</code></td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">纵向深度坐标 (<span class="math inline">\(0-120\)</span>)，表征向对方球门推进的垂直穿透力。</td>
<td style="text-align: left;">经 <code>allclean()</code> 展平提取。</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>空间坐标基础</strong></td>
<td style="text-align: left;"><code>location.y</code></td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">横向宽度坐标 (<span class="math inline">\(0-80\)</span>)，表征由边路向“Zone 14”中路的向心度。</td>
<td style="text-align: left;">经 <code>allclean()</code> 展平提取。</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>赛事时序基准</strong></td>
<td style="text-align: left;"><code>match_id</code></td>
<td style="text-align: left;">Integer</td>
<td style="text-align: left;">单场比赛的全局唯一标识符，用于切分并隔离单场赛事表现。</td>
<td style="text-align: left;">基础元数据直取保留。</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>赛事时序基准</strong></td>
<td style="text-align: left;"><code>minute</code> / <code>second</code></td>
<td style="text-align: left;">Integer</td>
<td style="text-align: left;">动作发生的精确时间戳。</td>
<td style="text-align: left;">用于 <code>arrange</code> 排序纠偏。</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>动作本体属性</strong></td>
<td style="text-align: left;"><code>type.name</code></td>
<td style="text-align: left;">Character</td>
<td style="text-align: left;">记录射门、传球、解围等泛用基础动作类型。</td>
<td style="text-align: left;">用于匹配 <span class="math inline">\(S_{base}\)</span> 动作初始赋分。</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>动作本体属性</strong></td>
<td style="text-align: left;"><code>pass.type.name</code></td>
<td style="text-align: left;">Character</td>
<td style="text-align: left;">传球动作子分类，精准识别定位球（如 Corner, Free Kick）。</td>
<td style="text-align: left;">用于赋予静态球权特定的空间豁免权重。</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>战术环境约束</strong></td>
<td style="text-align: left;"><code>under_pressure</code></td>
<td style="text-align: left;">Logical</td>
<td style="text-align: left;">二元布尔值，判定技术动作是否在对方高压防守下完成。</td>
<td style="text-align: left;">将原始缺失值 (NA) 统一插补为 <code>FALSE</code>。</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>战术环境约束</strong></td>
<td style="text-align: left;"><code>pass.height.name</code></td>
<td style="text-align: left;">Character</td>
<td style="text-align: left;">传球高度分类（Ground, Low, High Pass），反映球权控制质量。</td>
<td style="text-align: left;">直接截取分类并提取属性。</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>末端执行结果</strong></td>
<td style="text-align: left;"><code>pass.shot_assist</code></td>
<td style="text-align: left;">Logical</td>
<td style="text-align: left;">判定该传球是否直接转化为队友射门（助攻/关键传球）。</td>
<td style="text-align: left;">用于在模型中触发高额正向奖励权重。</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>末端执行结果</strong></td>
<td style="text-align: left;"><code>dribble.outcome.name</code></td>
<td style="text-align: left;">Character</td>
<td style="text-align: left;">记录单对单盘带过人突破的结果状态（成功/被抢断）。</td>
<td style="text-align: left;">鉴别前场有效推进与失误。</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>末端执行结果</strong></td>
<td style="text-align: left;"><code>pass.outcome.name</code></td>
<td style="text-align: left;">Character</td>
<td style="text-align: left;">追踪传球最终结果，识别非受迫性传球失误与球权易主。</td>
<td style="text-align: left;">用于触发模型中的战术失误负分惩罚机制。</td>
</tr>
</tbody>
</table>
<p>经过以上结构重塑、降噪提取与特征工程处理，原本嵌套冗杂的底层比赛日志被转化为高度结构化、时空属性完备且战术指向明确的二维特征矩阵。</p>
</section>
<section id="数据规模与样本清洗结果" class="level2">
<h2 class="anchored" data-anchor-id="数据规模与样本清洗结果">2.5 数据规模与样本清洗结果</h2>
<p>本研究通过 StatsBomb API 完整获取了 2015/2016 赛季德国足球甲级联赛（1. Bundesliga）的赛事事件数据。该赛季共包含 306 场比赛，API 初始抓取的原始事件记录总数高达 1,047,721 条。</p>
<p>在数据清洗阶段，本研究对原始样本进行了严格的过滤与预处理。首先，剔除了与实际比赛战术动作无关的结构性记录（如“首发名单 Starting XI”、“半场开始/结束 Half Start/End”等），共计剔除 8,466 条；其次，针对核心变量 <code>under_pressure</code>（防守压力）在 StatsBomb 数据源中的记录特性（仅在受压迫时标记为 True，无压迫时为空值），本研究将其缺失值（共计 847,427 条，占比约 80.88%）统一插补为 <code>FALSE</code>，以还原真实的无压迫比赛情境。最后，在计算战术价值（Z值）模型时，剔除了 25,813 条缺乏有效空间坐标或关键属性缺失的残缺记录。</p>
<p>经过上述严密的清洗流程，最终进入核心建模与空间插值分析的有效事件样本量为 1,013,442 条。具体的样本筛选漏斗与核心事件构成详见表 与表 。</p>
<p><strong>表：数据清洗与样本筛选流程表</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">筛选步骤</th>
<th style="text-align: left;">处理操作</th>
<th style="text-align: center;">剔除/修改样本量</th>
<th style="text-align: center;">剩余有效样本量</th>
<th style="text-align: left;">备注</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>1. 原始数据获取</strong></td>
<td style="text-align: left;">从 API 抓取 15/16 赛季全量事件</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;"><strong>1,047,721</strong></td>
<td style="text-align: left;">涵盖 306 场有效比赛</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>2. 剔除非战术事件</strong></td>
<td style="text-align: left;">过滤首发名单、半场起止等哨音事件</td>
<td style="text-align: center;">- 8,466</td>
<td style="text-align: center;"><strong>1,039,255</strong></td>
<td style="text-align: left;">仅保留场上实质性战术动作</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>3. 压力变量缺失插补</strong></td>
<td style="text-align: left;">将 <code>under_pressure</code> 的 NA 值转为 FALSE</td>
<td style="text-align: center;">修改 847,427</td>
<td style="text-align: center;"><strong>1,039,255</strong></td>
<td style="text-align: left;">还原无防守压迫的常态情境</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>4. 坐标与变量清洗</strong></td>
<td style="text-align: left;">剔除缺失空间坐标 (x,y) 及无法计值的记录</td>
<td style="text-align: center;">- 25,813</td>
<td style="text-align: center;"><strong>1,013,442</strong></td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>5. 最终建模样本</strong></td>
<td style="text-align: left;"><strong>进入战术价值 Z 模型与分析的总量</strong></td>
<td style="text-align: center;"><strong>-</strong></td>
<td style="text-align: center;"><strong>1,013,442</strong></td>
<td style="text-align: left;"><strong>构成最终实证分析的底层数据集</strong></td>
</tr>
</tbody>
</table>
<p><strong>表：最终样本中核心事件类型与防守压力分布</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">核心事件类型 (Event Type)</th>
<th style="text-align: center;">样本数量 (Count)</th>
<th style="text-align: center;">占总样本比例 (%)</th>
<th style="text-align: center;">其中受压迫比例 (Pressure Rate)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">传球 (Pass)</td>
<td style="text-align: center;">283,624</td>
<td style="text-align: center;">27.99%</td>
<td style="text-align: center;">15.22%</td>
</tr>
<tr class="even">
<td style="text-align: left;">接球 (Ball Receipt*)</td>
<td style="text-align: center;">260,021</td>
<td style="text-align: center;">25.66%</td>
<td style="text-align: center;">18.42%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">推进带球 (Carry)</td>
<td style="text-align: center;">204,732</td>
<td style="text-align: center;">20.20%</td>
<td style="text-align: center;">22.46%</td>
</tr>
<tr class="even">
<td style="text-align: left;">施压 (Pressure)</td>
<td style="text-align: center;">93,333</td>
<td style="text-align: center;">9.21%</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">球权恢复 (Ball Recovery)</td>
<td style="text-align: center;">32,473</td>
<td style="text-align: center;">3.20%</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">对抗 (Duel)</td>
<td style="text-align: center;">28,352</td>
<td style="text-align: center;">2.80%</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">解围 (Clearance)</td>
<td style="text-align: center;">19,342</td>
<td style="text-align: center;">1.91%</td>
<td style="text-align: center;">25.21%</td>
</tr>
<tr class="even">
<td style="text-align: left;">封堵 (Block)</td>
<td style="text-align: center;">11,649</td>
<td style="text-align: center;">1.15%</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">守门员动作 (Goal Keeper)</td>
<td style="text-align: center;">11,340</td>
<td style="text-align: center;">1.12%</td>
<td style="text-align: center;">1.70%</td>
</tr>
<tr class="even">
<td style="text-align: left;">停球失误 (Miscontrol)</td>
<td style="text-align: center;">11,204</td>
<td style="text-align: center;">1.11%</td>
<td style="text-align: center;">46.66%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">其他战术动作</td>
<td style="text-align: center;">57,372</td>
<td style="text-align: center;">5.65%</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>总计 (Total)</strong></td>
<td style="text-align: center;"><strong>1,013,442</strong></td>
<td style="text-align: center;"><strong>100.00%</strong></td>
<td style="text-align: center;"><strong>-</strong></td>
</tr>
</tbody>
</table>
<p><em>(注：施压、恢复球权、对抗、封堵等防守端动作，其本身属于无球/破坏状态，StatsBomb 默认不计入“持球受压迫”比例)</em></p>
</section>
</section>
<section id="第三章-概念界定与理论模型介绍" class="level1">
<h1>第三章 概念界定与理论模型介绍</h1>
<section id="传统空间分布估计模型" class="level2">
<h2 class="anchored" data-anchor-id="传统空间分布估计模型">3.1 传统空间分布估计模型</h2>
<section id="核密度估计法-kernel-density-estimation-kde" class="level3">
<h3 class="anchored" data-anchor-id="核密度估计法-kernel-density-estimation-kde">3.1.1 核密度估计法 (Kernel Density Estimation, KDE)</h3>
<p>核密度估计法是目前足球数据分析中生成“热点图”最广泛使用的非参数化空间统计方法。其基本原理是在空间中每一个离散的事件发生点（如球员触球坐标）上放置一个平滑的核函数，通过将所有点的核函数进行叠加，计算出整个二维空间内的概率密度表面。</p>
<p>对于二维足球场空间，其核密度估计的数学表达式通常为：</p>
<p><span class="math display">\[\hat{f}(x,y) = \frac{1}{n h_x h_y} \sum_{i=1}^{n} K\left(\frac{x - x_i}{h_x}, \frac{y - y_i}{h_y}\right)\]</span></p>
<p>其中，<span class="math inline">\(n\)</span> 为样本点总数，<span class="math inline">\(h_x, h_y\)</span> 为人为设定的平滑带宽，<span class="math inline">\(K\)</span> 为核函数（通常选用高斯核）。</p>
<p><strong>概念局限性</strong>：KDE 本质上刻画的是“事件发生的频率密度”。在足球场景中，它只能回答“球员在哪里触球最多”，却无法回答“哪里的触球最具战术威胁”。同时，其平滑结果极度依赖主观设定的带宽 <span class="math inline">\(h\)</span>，且假设空间中的独立事件彼此无关，忽略了足球运动中天然存在的空间自相关性。</p>
</section>
</section>
<section id="空间统计学与克里金插值模型" class="level2">
<h2 class="anchored" data-anchor-id="空间统计学与克里金插值模型">3.2 空间统计学与克里金插值模型</h2>
<p>为了克服 KDE 的局限，本研究引入地统计学模型。地统计学的核心逻辑在于，它超越了传统非参数平滑算法的机械刻画，深刻承认了空间分布数据所独具的“结构性”与“随机性”双重特征。具体而言，“结构性”是指足球场上的战术价值并非随机散布，而是受到距离衰减规律和战术阵型的约束，呈现出强烈的空间依赖与连续演变趋势；而“随机性”则表征了在复杂的体育竞技环境中，由于测量误差、球员个体决策偏差以及不可预测的球权物理反弹所造成的局部空间异质性。通过统筹这两种特性，地统计学模型能够以更为严密的数学逻辑，还原出高度契合真实比赛环境的空间价值场。</p>
<section id="空间自相关与战术溢出效应" class="level3">
<h3 class="anchored" data-anchor-id="空间自相关与战术溢出效应">3.2.1 空间自相关与战术溢出效应</h3>
<p>空间自相关是地统计学区别于经典统计学的核心概念。经典统计学通常假设样本之间是独立同分布的，但在处理真实世界的空间数据时，这一假设往往失效。1970年，瓦尔多·托布勒（Waldo Tobler）提出了著名的“托布勒地理学第一定律”：“任何事物都是与其他事物相关的，但相近的事物关联更紧密。”这一定律奠定了空间自相关理论的基石，即空间位置上相近的变量取值之间存在着内在的统计学依赖关系。</p>
<p>在高度复杂且动态变化的足球场上，这一地理学定律展现出了极强的战术适用性。足球比赛本质上是对空间的争夺与利用，球场上的战术事件绝非孤立发生，而是具有显著的“空间溢出效应”。某一区域的高质量控球，往往会跨越物理距离，对其相邻甚至更远的区域产生战术辐射和防守牵制。</p>
<p>具体而言，这种空间自相关性在足球战术中主要体现在以下两个维度：</p>
<ol type="1">
<li><strong>进攻威胁的辐射性（正向空间自相关）</strong>：当进攻方在诸如肋部区域或大禁区前沿完成一次极具威胁的持球推进时，不仅该坐标点本身的战术价值剧增，其相邻的禁区中路或底线传中区的潜在威胁值也会随之呈现指数级上升。这种高价值区域在空间上的聚集特征，在统计学上表现为显著的正向空间自相关。</li>
<li><strong>防守重心的拉扯（防守引力效应）</strong>：某一边路的高频触球会形成防守引力，迫使防守方阵型整体倾斜。这种局部空间的拥挤，会在球场的另一侧（弱侧）暴露出高价值的开阔空间。这种由一侧的行动引起另一侧价值变化的联动关系，进一步证明了球场空间是一个不可割裂的有机整体。</li>
</ol>
<p>传统基于核密度估计或简单网格划分的统计方法，其致命弱点正是将球场上每一米、每一次触球都视为相互独立的离散事件，粗暴地剥离了上述的空间依赖关系。因此，本研究引入空间自相关理论，目的正是为了在数学层面上还原足球场上点与点之间隐蔽的战术联系。只有承认并量化了这种空间自相关性，我们才能顺理成章地使用变异函数去测量这种战术辐射的有效半径，进而为克里金插值提供科学的推断依据。</p>
</section>
<section id="变异函数" class="level3">
<h3 class="anchored" data-anchor-id="变异函数">3.2.2 变异函数</h3>
<p>变异函数（或半变异函数）是量化空间自相关性的核心数学工具。它描述了空间变量随着距离的增加，其空间依赖性是如何减弱的。 设 <span class="math inline">\(Z(x_{\alpha})\)</span> 为球场上位置 <span class="math inline">\(x_{\alpha}\)</span> 处的球权战术价值，定义其空间实验变异函数 <span class="math inline">\(\gamma(h)\)</span> 为：</p>
<p><span class="math display">\[\gamma(h) = \frac{1}{2N(h)} \sum_{i=1}^{N(h)} [Z(x_i) - Z(x_i + h)]^2\]</span></p>
<p>其中，<span class="math inline">\(h\)</span> 为空间滞后距离（即两点间的距离），<span class="math inline">\(N(h)\)</span> 为距离为 <span class="math inline">\(h\)</span> 的样本点对数量。</p>
<p>本研究采用<strong>指数模型</strong>对实验变异函数进行理论拟合。其拟合结果包含三个极其重要的地统计学概念：</p>
<ol type="1">
<li><strong>块金值 (Nugget)</strong>：当距离 <span class="math inline">\(h\)</span> 趋近于 0 时，变异函数不为 0 的常数项，代表由测量误差或微观随机性（如足球场上不可预测的球权反弹）造成的空间异质性。</li>
<li><strong>基台值 (Sill)</strong>：随着距离的增加，变异函数达到平稳状态的极限值，代表变量在全场的总空间变异程度。</li>
<li><strong>变程 (Range)</strong>：变异函数达到基台值时的距离。在足球语境中，变程具有极其重要的战术意义，它代表了球员战术动作在球场上的“最大有效辐射半径”。超过此距离，事件之间即被视为统计独立。</li>
</ol>
</section>
<section id="普通克里金插值法及其数学推导" class="level3">
<h3 class="anchored" data-anchor-id="普通克里金插值法及其数学推导">3.2.3 普通克里金插值法及其数学推导</h3>
<p>普通克里金法是地统计学中应用最为广泛的空间局部插值方法。与传统基于纯几何距离的反距离权重法（IDW）不同，普通克里金法不仅仅考虑已知点与预测点之间的距离，更通过变异函数将已知点之间的空间拓扑关系（如数据的聚集与遮蔽效应）纳入计算。它被称为“最佳线性无偏估计”（BLUE），其核心在于在满足无偏性的前提下，使得预测误差的方差最小。</p>
<section id="理论前提平稳性假设" class="level4">
<h4 class="anchored" data-anchor-id="理论前提平稳性假设">1. 理论前提：平稳性假设</h4>
<p>普通克里金法的应用建立在内蕴平稳性假设之上。在足球场空间分布的语境下，该假设意味着：</p>
<ol type="1">
<li><strong>期望的恒定性</strong>：在局部的搜索邻域内，球权战术价值 <span class="math inline">\(Z(x)\)</span> 的数学期望是一个常数，虽未知但固定，即 <span class="math inline">\(E[Z(x)] = c\)</span>（常数）。</li>
<li><strong>增量的平稳性</strong>：球场上任意两点 <span class="math inline">\(x_i\)</span> 和 <span class="math inline">\(x_i+h\)</span> 处的球权价值之差的方差，仅与两点间的空间向量 <span class="math inline">\(h\)</span> 有关，而与它们在球场上的绝对位置无关。这一特性正是前文构建变异函数 <span class="math inline">\(\gamma(h)\)</span> 的理论基础。</li>
</ol>
<p>尽管足球场上的战术价值存在显著的向心与向前趋势，但本研究在将在构建 <span class="math inline">\(Z\)</span> 模型时，已通过引入空间权重函数（<span class="math inline">\(W_{space}\)</span>）将宏观的空间漂移显性化地内化于变量自身。因此，经过空间赋权后的 <span class="math inline">\(Z\)</span> 值在局部搜索邻域内已满足内蕴平稳性假设，使用普通克里金能有效避免对空间趋势的重复计算，还能在保证无偏估计的同时降低方程求解的矩阵奇异性风险。</p>
</section>
<section id="线性无偏估计的构建" class="level4">
<h4 class="anchored" data-anchor-id="线性无偏估计的构建">2. 线性无偏估计的构建</h4>
<p>对于球场上任意未发生实际触球的空白网格点 <span class="math inline">\(x_0\)</span>，可以利用其周围邻域内的 <span class="math inline">\(n\)</span> 个已知有效样本点 <span class="math inline">\(Z(x_1), Z(x_2), \dots, Z(x_n)\)</span>，来估算该点的战术价值 <span class="math inline">\(Z^*(x_0)\)</span>。普通克里金法采用已知样本值的线性组合来进行预测：</p>
<p><span class="math display">\[Z^*(x_0) = \sum_{i=1}^{n} \lambda_i Z(x_i)\]</span></p>
<p>其中，<span class="math inline">\(\lambda_i\)</span> 为赋予第 <span class="math inline">\(i\)</span> 个已知样本点的克里金权重系数。</p>
<p>为了保证该估计是无偏的，即估计值的期望必须等于真实值的期望，必须满足以下条件：</p>
<p><span class="math display">\[E[Z^*(x_0) - Z(x_0)] = 0\]</span></p>
<p>代入内蕴平稳性假设 <span class="math inline">\(E[Z(x)] = c\)</span>，可推导出权重系数的无偏约束条件：</p>
<p><span class="math display">\[\sum_{i=1}^{n} \lambda_i = 1\]</span></p>
</section>
<section id="估计方差最小化与拉格朗日乘数法" class="level4">
<h4 class="anchored" data-anchor-id="估计方差最小化与拉格朗日乘数法">3. 估计方差最小化与拉格朗日乘数法</h4>
<p>克里金法被称为“最佳（Best）”估计，是因为它要在所有满足 <span class="math inline">\(\sum \lambda_i = 1\)</span> 的线性组合中，寻找到一组最优的权重 <span class="math inline">\(\lambda_i\)</span>，使得预测值与真实值之间的估计方差最小。 估计方差 <span class="math inline">\(\sigma_E^2\)</span> 可表示为：</p>
<p><span class="math display">\[\sigma_E^2 = Var[Z^*(x_0) - Z(x_0)]\]</span></p>
<p>将该方差表达式利用前文定义的变异函数 <span class="math inline">\(\gamma(h)\)</span> 展开，可以将最小化方差的优化目标转化为变异函数的表达式：</p>
<p><span class="math display">\[\sigma_E^2 = 2 \sum_{i=1}^{n} \lambda_i \gamma(x_i, x_0) - \sum_{i=1}^{n} \sum_{j=1}^{n} \lambda_i \lambda_j \gamma(x_i, x_j)\]</span></p>
<p>这是一个带有等式约束的非线性极值问题。为了求解使得 <span class="math inline">\(\sigma_E^2\)</span> 最小的 <span class="math inline">\(\lambda_i\)</span>，这里引入拉格朗日乘数法。构造拉格朗日目标函数 <span class="math inline">\(L\)</span>：</p>
<p><span class="math display">\[L(\lambda_i, \mu) = \sigma_E^2 + 2\mu \left( \sum_{i=1}^{n} \lambda_i - 1 \right)\]</span></p>
<p>其中，<span class="math inline">\(\mu\)</span> 为拉格朗日乘数。</p>
</section>
<section id="普通克里金方程组" class="level4">
<h4 class="anchored" data-anchor-id="普通克里金方程组">4. 普通克里金方程组</h4>
<p>为了求得极小值，将目标函数 <span class="math inline">\(L\)</span> 分别对所有的权重 <span class="math inline">\(\lambda_i\)</span> 和拉格朗日乘数 <span class="math inline">\(\mu\)</span> 求偏导数，并令偏导数等于零：</p>
<p><span class="math display">\[\frac{\partial L}{\partial \lambda_i} = 0 \quad (i = 1, 2, \dots, n)\]</span></p>
<p><span class="math display">\[\frac{\partial L}{\partial \mu} = 0\]</span></p>
<p>经过化简，得到普通克里金方程组：</p>
<p><span class="math display">\[\begin{cases}
\sum_{j=1}^{n} \lambda_j \gamma(x_i, x_j) + \mu = \gamma(x_i, x_0) &amp; (i = 1, 2, \dots, n) \\
\sum_{i=1}^{n} \lambda_i = 1 &amp;
\end{cases}\]</span></p>
<p>在实际的足球空间建模计算中（如本研究中调用的 <code>gstat</code> 核心算法），计算机会将上述方程组转化为矩阵运算形式：</p>
<p><span class="math display">\[\begin{bmatrix}
\gamma(x_1, x_1) &amp; \cdots &amp; \gamma(x_1, x_n) &amp; 1 \\
\vdots &amp; \ddots &amp; \vdots &amp; \vdots \\
\gamma(x_n, x_1) &amp; \cdots &amp; \gamma(x_n, x_n) &amp; 1 \\
1 &amp; \cdots &amp; 1 &amp; 0
\end{bmatrix}
\begin{bmatrix}
\lambda_1 \\ \vdots \\ \lambda_n \\ \mu
\end{bmatrix}
=
\begin{bmatrix}
\gamma(x_1, x_0) \\ \vdots \\ \gamma(x_n, x_0) \\ 1
\end{bmatrix}\]</span></p>
<p>通过对左侧的半方差矩阵求逆，即可解出每一个已知触球点对未知网格点的最优权重 <span class="math inline">\(\lambda_i\)</span>。</p>
</section>
<section id="克里金方差与数据置信度量化" class="level4">
<h4 class="anchored" data-anchor-id="克里金方差与数据置信度量化">5. 克里金方差与数据置信度量化</h4>
<p>将求解出的最优权重 <span class="math inline">\(\lambda_i\)</span> 代回估计方差公式中，即可求得克里金预测方差（<span class="math inline">\(\sigma_K^2\)</span>）：</p>
<p><span class="math display">\[\sigma_K^2 = \sum_{i=1}^{n} \lambda_i \gamma(x_i, x_0) + \mu\]</span></p>
<p>在足球战术分析中，克里金方差具有颠覆性的实际意义。传统基于核密度（KDE）的热点图只能给出预测的绝对值，却无法告诉你这个预测结果的偏移可能性。而克里金模型输出的 <span class="math inline">\(\sigma_K^2\)</span> 完美弥补了这一空白：当 <span class="math inline">\(\sigma_K^2\)</span> 较小时，说明该区域附近的真实触球样本点丰富且规律性强，战术价值的预测可信度极高；反之，若某一边角区域 <span class="math inline">\(\sigma_K^2\)</span> 畸高，模型则会在数学上发出预警——该区域的热度预测可能因样本稀疏而存在较大误差。这种对预测不确定性的量化，为足球教练组的实战排兵布阵确立了科学的风险评估边界。</p>
</section>
</section>
</section>
<section id="足球球权战术价值评价体系z-模型的构建" class="level2">
<h2 class="anchored" data-anchor-id="足球球权战术价值评价体系z-模型的构建">3.3 足球球权战术价值评价体系（Z 模型）的构建</h2>
<p>本研究的根本创新在于将原本离散、无属性的坐标点，转化为具有明确战术指向的“价值点”。为此，本研究摒弃了单一维度的评价方式，构建了多维度的“球权战术价值（<span class="math inline">\(Z\)</span>）”乘法模型。在正式确立模型公式之前，本节将首先从战术理论与客观数据双重维度，论证核心特征选取的科学性。</p>
<section id="模型特征选择的理论与数据依据" class="level3">
<h3 class="anchored" data-anchor-id="模型特征选择的理论与数据依据">3.3.1 模型特征选择的理论与数据依据</h3>
<p>本研究的 Z 模型包含四个核心维度：动作类型、空间位置、防守压迫与传球高度。其选取依据不仅立足于前沿的运动科学理论，更得到了德甲 15/16 赛季全样本数据的客观支撑。</p>
<p>本模型所计算的 <span class="math inline">\(Z\)</span> 分数，衡量的是特定战术动作在球场空间内产生的<strong>“整体战术重要性（Tactical Importance）”与“空间控制贡献度（Spatial Value Contribution）”</strong>，而非传统意义上单一指向对方球门的“进攻威胁值（如 Expected Threat, xT）”。</p>
<p>基于这一核心量纲定义，本模型在评价体系中打破了传统数据分析中攻防两端的割裂。在真实的比赛博弈中，一次极具威胁的射门（试图改变比分的进攻极端动作）与一次关键的门将扑救或禁区内解围（试图阻止比分改变的防守极端动作），在改变或维持比赛动态平衡（Match State）的作用权重上具有同等的核心战略地位。</p>
<p>因此，在本模型的基础战术分（<span class="math inline">\(S_{base}\)</span>）设定中，射门与关键扑救被置于同一标度量级（均赋予最高的 10 分基础分），解围与封堵等核心防守动作同样被赋予高分。这种“绝对值化”的评估逻辑，旨在将攻防两端的高价值战术节点统一投射到同一个“比赛影响力”标尺上，从而为后续在全场二维坐标系中生成连续的、包含攻防双向权重的战术价值空间场（Spatial Value Field）提供逻辑自洽的数学基础。</p>
<section id="动作类型维度-s_base-的选取依据" class="level4">
<h4 class="anchored" data-anchor-id="动作类型维度-s_base-的选取依据">1. 动作类型维度 (<span class="math inline">\(S_{base}\)</span>) 的选取依据</h4>
<p><strong>理论支持：基于马尔可夫链的“动作状态转换”理论</strong> 在现代足球量化分析中，Decroos 等人 (2019) 提出的 VAEP (Valuing Actions by Estimating Probabilities) 框架确立了基于事件驱动（Event-driven）的动作评价范式。该理论将足球比赛视为一系列离散动作的状态转移过程，证明了传球、射门、防守解围等不同行为对预期进球（xG）的贡献度存在显著的层级差异。本研究设定的基础动作分（<span class="math inline">\(S_{base}\)</span>）正是基于这一状态转换理论，旨在对不同技术动作赋予其天然的期望收益权重。</p>
<p><strong>数据支持：定位球的高转化率溢价</strong> 传统基于欧氏距离的空间模型往往会严重低估角球的价值，因为其发生地位于球场四个角落（远离球门中心）。然而，对德甲数据的实证检验推翻了这一直觉：</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/EDA_%E4%BC%A0%E7%90%83%E7%B1%BB%E5%9E%8B%E5%8A%A9%E6%94%BB%E7%8E%87%E5%AF%B9%E6%AF%94.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>传球类型助攻率对比率</figcaption>
</figure>
</div>
<p>数据结果显示，角球直接形成射门助的概率远高于运动战常规传球。这证明了定位球具有跨越空间距离直接威胁球门的能力，为后续模型中赋予定位球极高的基础分与空间豁免权提供了坚实依据。</p>
</section>
<section id="空间位置维度-w_space-的选取依据" class="level4">
<h4 class="anchored" data-anchor-id="空间位置维度-w_space-的选取依据">2. 空间位置维度 (<span class="math inline">\(W_{space}\)</span>) 的选取依据</h4>
<p><strong>理论支持：空间效能与“Zone 14”理论</strong> 足球场上的空间效能并非均匀分布。Horn 等人 (2002) 提出的‘Zone 14（即大禁区前沿中路区域）’理论指出，在该区域的有效触球与最终进球转化率呈高度正相关。同时，Fernandez 与 Bornn (2018) 的开阔空间模型也证实了进攻向心力对防守阵型的破坏作用。基于此，本模型引入空间坐标，构建了‘横向向心与纵向推进’的双维空间权重。</p>
<p><strong>数据验证：射门事件的二维核密度分布</strong> 为验证上述理论，本研究提取全赛季射门数据并绘制了空间密度分布图：</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/EDA_%E5%B0%84%E9%97%A8%E5%AF%86%E5%BA%A6%E5%88%86%E5%B8%83.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>射门密度分布</figcaption>
</figure>
</div>
<p>如核密度图所示，绝对得分机会高度向心聚拢于对方禁区中路（<span class="math inline">\(X &gt; 100, Y \in [30, 50]\)</span>）。这在统计学上完美印证了“向心推进”的战术溢价规律。</p>
</section>
<section id="防守压迫维度-c_pressure-的选取依据" class="level4">
<h4 class="anchored" data-anchor-id="防守压迫维度-c_pressure-的选取依据">3. 防守压迫维度 (<span class="math inline">\(C_{pressure}\)</span>) 的选取依据</h4>
<p><strong>理论支持：生态动力学中的“约束限制”理论</strong> 运动生态动力学（Ecological Dynamics）认为，运动员的决策和动作价值不能脱离环境约束（Constraints）。传统的数据统计存在“数据欺骗性”——后卫在无压力下的横传与中场在被包夹下的出球，其战术难度截然不同。StatsBomb 数据集率先引入的“受迫（Under Pressure）”标签，使得剥离“无效控球”成为可能。</p>
<p><strong>数据验证：防守压力下的失误率激增</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/EDA_%E4%B8%8D%E5%90%8C%E5%8E%8B%E5%8A%9B%E5%A4%B1%E8%AF%AF%E7%8E%87%E5%AF%B9%E6%AF%94.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>不同压力失误率对比</figcaption>
</figure>
</div>
<p>统计证实，受压迫状态下的技术失误率呈倍数级增加。基于“风险与收益对等”法则，在极端防守约束下完成的高难度战术动作理应获得溢价补偿，这为设定压力系数提供了实证支撑。</p>
</section>
<section id="传球高度维度-q_quality-的选取依据" class="level4">
<h4 class="anchored" data-anchor-id="传球高度维度-q_quality-的选取依据">4. 传球高度维度 (<span class="math inline">\(Q_{quality}\)</span>) 的选取依据</h4>
<p><strong>理论支持：瓜迪奥拉的“地面控制”战术哲学</strong> 本研究的实证对象为 15/16 赛季的德甲联赛（瓜迪奥拉执教时期）。现代传控足球的战术哲学极度强调对球权的绝对控制，而地面传球（Ground Pass）相比于高空球（High Pass）拥有更高的球权保留率和更低的失误方差。因此，引入传球高度作为控球质量修正参数（<span class="math inline">\(Q_{quality}\)</span>），是对赛事时代背景与主流战术理念的客观还原。</p>
<p><strong>数据验证：随着传球高度失误率激增</strong> <img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/EDA_%E4%BC%A0%E7%90%83%E9%AB%98%E5%BA%A6%E5%A4%B1%E8%AF%AF%E7%8E%87%E5%AF%B9%E6%AF%94.png?raw=true" class="img-fluid" alt="传球高度失误率对比"></p>
</section>
</section>
<section id="z-模型的多维特征乘法构建" class="level3">
<h3 class="anchored" data-anchor-id="z-模型的多维特征乘法构建">3.3.2 Z 模型的多维特征乘法构建</h3>
<p>在确立上述特征维度的合理性后，本研究采用多维特征乘法模型构建最终的球权战术价值指标 <span class="math inline">\(Z\)</span>。公式定义如下：</p>
<p><span class="math display">\[Z = S_{base} \times W_{space}(x, y) \times C_{pressure} \times Q_{quality}\]</span></p>
<p>各子模块的具体数学设定如下：</p>
<section id="基础动作分-s_base" class="level4">
<h4 class="anchored" data-anchor-id="基础动作分-s_base">1. 基础动作分 (<span class="math inline">\(S_{base}\)</span>)</h4>
<p>模型依据战术影响程度，对不同类型的技术动作进行固有威胁等级赋值（详见表2-1）。特别设立了针对失误行为的负分机制。</p>
<p><strong>表2-1 基础动作战术价值等级赋值表</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>动作类型 (Event Type)</th>
<th><span class="math inline">\(S_{base}\)</span> 分值</th>
<th>战术含义</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>射门 / 关键扑救 (Shot / Save)</td>
<td>10.0</td>
<td>直接改变比分或阻止得分</td>
</tr>
<tr class="even">
<td>助攻 / 关键传球 (Key Pass)</td>
<td>8.0</td>
<td>直接创造射门机会</td>
</tr>
<tr class="odd">
<td>门线解围 / 封堵 (Clearance / Block)</td>
<td>8.0</td>
<td>破坏绝对得分机会</td>
</tr>
<tr class="even">
<td>角球 (Corner)</td>
<td>7.0</td>
<td>[特例]高价值定位球机会</td>
</tr>
<tr class="odd">
<td>任意球 / 拦截 / 抢断 / 过人</td>
<td>6.0</td>
<td>夺回球权或破坏防守结构</td>
</tr>
<tr class="even">
<td>对抗 / 施压 / 护球</td>
<td>4.0</td>
<td>有效的战术物理对抗</td>
</tr>
<tr class="odd">
<td>普通传球 / 推进</td>
<td>1.0</td>
<td>维持球权周转</td>
</tr>
<tr class="even">
<td>普通动作 (其他)</td>
<td>1.0</td>
<td>常规触球</td>
</tr>
<tr class="odd">
<td>失误 (Error/Loss)</td>
<td>-3.0</td>
<td>丢失球权或战术执行失败</td>
</tr>
</tbody>
</table>
</section>
<section id="多维空间权重-w_space" class="level4">
<h4 class="anchored" data-anchor-id="多维空间权重-w_space">2. 多维空间权重 (<span class="math inline">\(W_{space}\)</span>)</h4>
<p>该模块综合了纵向推进 (<span class="math inline">\(X\)</span>) 和横向向心 (<span class="math inline">\(Y\)</span>) 的位置价值。首先定义 Y 轴向心度函数 <span class="math inline">\(C_{y}(y)\)</span>，其中 <span class="math inline">\(y \in [0, 80]\)</span>：</p>
<p><span class="math display">\[C_{y}(y) = 1 - \frac{|y - 40|}{40}\]</span></p>
<p>该函数确保了中轴线 (<span class="math inline">\(y=40\)</span>) 取得最高分 1.0，向两侧边线线性递减至 0。</p>
<p>随后，根据动作性质将 <span class="math inline">\(W_{space}\)</span> 划分为五种应用情境：</p>
<ul>
<li><strong>情形 A：角球 (Corner)</strong> —— [特权豁免]：<span class="math inline">\(W_{space} = 2.5\)</span>（赋予理论最高权重，无视其边路发球的位置劣势）。</li>
<li><strong>情形 B：任意球 (Free Kick)</strong> —— [补偿豁免]：<span class="math inline">\(W_{space} = 2.0\)</span>。</li>
<li><strong>情形 C：防守动作</strong> —— 目标为保护己方球门：</li>
</ul>
<p><span class="math display">\[W_{space}(x, y) = 1 + \underbrace{\frac{120 - x}{120}}_{\text{后场保护}} + \underbrace{0.5 \times C_{y}(y)}_{\text{中路防守}}\]</span></p>
<ul>
<li><strong>情形 D：进攻动作</strong> —— 目标为攻击对方球门：</li>
</ul>
<p><span class="math display">\[W_{space}(x, y) = 1 + \underbrace{\frac{x}{120}}_{\text{前场推进}} + \underbrace{0.5 \times C_{y}(y)}_{\text{中路渗透}}\]</span></p>
<ul>
<li><strong>情形 E：失误 (Errors)</strong> —— <span class="math inline">\(W_{space} = 0.5\)</span>（进行空间降维，防止在对方危险区域失误反而获得高分变异）。</li>
</ul>
</section>
<section id="压力情景系数-c_pressure" class="level4">
<h4 class="anchored" data-anchor-id="压力情景系数-c_pressure">3. 压力情景系数 (<span class="math inline">\(C_{pressure}\)</span>)</h4>
<p>基于前文验证的对抗高风险属性，设定二元分段函数奖励抗压迫操作：</p>
<p><span class="math display">\[C_{pressure} = \begin{cases} 1.5, &amp; \text{if Under Pressure = TRUE} \\ 1.0, &amp; \text{if Under Pressure = FALSE} \end{cases}\]</span></p>
</section>
<section id="控球质量修正-q_quality" class="level4">
<h4 class="anchored" data-anchor-id="控球质量修正-q_quality">4. 控球质量修正 (<span class="math inline">\(Q_{quality}\)</span>)</h4>
<p>针对传球事件，以地面控制作为最优解进行质量修正：</p>
<p><span class="math display">\[Q_{quality} = \begin{cases} 0.8, &amp; \text{if High Pass (高空球)} \\ 0.9, &amp; \text{if Low Pass (半高球)} \\ 1.0, &amp; \text{if Ground Pass (地面球) or Non-Pass Actions} \end{cases}\]</span></p>
</section>
</section>
<section id="模型参数设定与稳健性检验" class="level3">
<h3 class="anchored" data-anchor-id="模型参数设定与稳健性检验">3.3.3 模型参数设定与稳健性检验</h3>
<section id="核心主观参数的设定逻辑" class="level4">
<h4 class="anchored" data-anchor-id="核心主观参数的设定逻辑">1. 核心主观参数的设定逻辑</h4>
<p>在本研究的战术价值 <span class="math inline">\(Z\)</span> 模型中，最终的估值由四个核心维度综合决定：基础战术分 (<span class="math inline">\(s_{base}\)</span>)、空间权重 (<span class="math inline">\(w_{space}\)</span>)、压力奖励系数 (<span class="math inline">\(c_{pressure}\)</span>) 以及传球高度惩罚 (<span class="math inline">\(q_{height}\)</span>)。由于足球比赛的复杂性与动态性，部分参数的初始权重需要结合赛事特征与领域先验知识进行设定：全局参数 (<span class="math inline">\(s_{base}\)</span> 与 <span class="math inline">\(w_{space}\)</span>)： 这两项参数构成了模型的基本底座。基础分依据事件类型（如射门、关键传球、失误）进行阶梯式赋分；空间权重则依据坐标位置和球场中心度进行计算，距离对方球门越近、越靠近中路，权重越高。情境触发参数 (<span class="math inline">\(c_{pressure}\)</span> 与 <span class="math inline">\(q_{height}\)</span>)： 这两项参数旨在还原真实的比赛高难度情境。对于在防守压迫下完成的动作，模型赋予 1.5倍 的压力奖励系数 (<span class="math inline">\(c_{pressure}\)</span>) 以表彰其更高的技术执行难度；对于传球高度，考虑到高空球和半高球的落点控制难度与丢失球权风险，模型分别施加了 0.8 与 0.9 的衰减系数 (<span class="math inline">\(q_{height}\)</span>)。在查阅得到的大部分文献中，均使用了主观设定的形式来进行计算相关模型，且这类战术上的模型更多依仗于使用者对于某一方面更为侧重而设定，对参数进行主观设定是较为合理的。</p>
</section>
<section id="多维参数敏感性分析-oat" class="level4">
<h4 class="anchored" data-anchor-id="多维参数敏感性分析-oat">2. 多维参数敏感性分析 (OAT)</h4>
<p>为了排查上述主观参数设定对模型整体估值体系可能产生的过度干扰，本研究引入了单因素敏感性分析（One-At-a-Time Sensitivity Analysis）。以基准模型为参照，依次将上述四个维度的参数分别上调和下调 10% 与 20%（其余参数保持基准值不变），并观察全联盟平均战术价值的变化幅度。结合敏感性分析结果表与折线图，可以得出以下稳健性结论：第一，情境触发参数未导致宏观估值失真。结果表明，模型对压力奖励系数 (<span class="math inline">\(c_{pressure}\)</span>) 和传球高度惩罚 (<span class="math inline">\(q_{height}\)</span>) 的主观扰动极不敏感。当这两项参数发生 ±20% 的大幅度变动时，全联盟的平均战术价值始终稳定在 2.43 至 2.48 的极窄区间内。这证明了针对特定比赛情境（受压迫、高空作业）所引入的局部权重调整，既能精准捕捉微观战术细节，又不会“绑架”整个大盘，避免了宏观估值体系的失真。第二，全局参数表现出预期的线性缩放特征。当基础战术分 (<span class="math inline">\(s_{base}\)</span>) 和空间权重 (<span class="math inline">\(w_{space}\)</span>) 发生浮动时，大盘均值呈现出严格的线性缩放（均值从下调 20% 时的 1.97 稳步上升至上调 20% 时的 2.95）。这种同步的等比例缩放符合数学公式的设计预期。它表明，全局变量的改变仅仅是拉伸或压缩了战术价值的“刻度尺”，而并未破坏模型内部对不同球员和不同区域价值排序的相对关系，其核心标准差（SD）也随之保持等比例放缩（从 3.27 升至 4.91）。</p>
</section>
</section>
<section id="多维主观参数敏感性分析结果-oat" class="level3">
<h3 class="anchored" data-anchor-id="多维主观参数敏感性分析结果-oat">多维主观参数敏感性分析结果 (OAT)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">测试参数 (Parameter)</th>
<th style="text-align: center;">扰动比例</th>
<th style="text-align: center;">均值 (Mean Z)</th>
<th style="text-align: center;">标准差 (SD Z)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>基础战术分 (<span class="math inline">\(s_{base}\)</span>)</strong></td>
<td style="text-align: center;">-20%</td>
<td style="text-align: center;">1.747</td>
<td style="text-align: center;">0.342</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">-10%</td>
<td style="text-align: center;">1.965</td>
<td style="text-align: center;">0.385</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"><strong>0% (基准)</strong></td>
<td style="text-align: center;"><strong>2.183</strong></td>
<td style="text-align: center;"><strong>0.428</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">+10%</td>
<td style="text-align: center;">2.402</td>
<td style="text-align: center;">0.471</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">+20%</td>
<td style="text-align: center;">2.620</td>
<td style="text-align: center;">0.513</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>空间权重 (<span class="math inline">\(w_{space}\)</span>)</strong></td>
<td style="text-align: center;">-20%</td>
<td style="text-align: center;">1.747</td>
<td style="text-align: center;">0.342</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">-10%</td>
<td style="text-align: center;">1.965</td>
<td style="text-align: center;">0.385</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"><strong>0% (基准)</strong></td>
<td style="text-align: center;"><strong>2.183</strong></td>
<td style="text-align: center;"><strong>0.428</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">+10%</td>
<td style="text-align: center;">2.402</td>
<td style="text-align: center;">0.471</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">+20%</td>
<td style="text-align: center;">2.620</td>
<td style="text-align: center;">0.513</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>压力奖励系数 (<span class="math inline">\(c_{pressure}\)</span>)</strong></td>
<td style="text-align: center;">-20%</td>
<td style="text-align: center;">2.052</td>
<td style="text-align: center;">0.199</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">-10%</td>
<td style="text-align: center;">2.118</td>
<td style="text-align: center;">0.310</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"><strong>0% (基准)</strong></td>
<td style="text-align: center;"><strong>2.183</strong></td>
<td style="text-align: center;"><strong>0.428</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">+10%</td>
<td style="text-align: center;">2.249</td>
<td style="text-align: center;">0.548</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">+20%</td>
<td style="text-align: center;">2.315</td>
<td style="text-align: center;">0.669</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>传球高度惩罚 (<span class="math inline">\(q_{height}\)</span>)</strong></td>
<td style="text-align: center;">-20%</td>
<td style="text-align: center;">2.144</td>
<td style="text-align: center;">0.466</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">-10%</td>
<td style="text-align: center;">2.164</td>
<td style="text-align: center;">0.444</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"><strong>0% (基准)</strong></td>
<td style="text-align: center;"><strong>2.183</strong></td>
<td style="text-align: center;"><strong>0.428</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">+10%</td>
<td style="text-align: center;">2.203</td>
<td style="text-align: center;">0.419</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">+20%</td>
<td style="text-align: center;">2.223</td>
<td style="text-align: center;">0.419</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/Model_%E5%A4%9A%E7%BB%B4%E5%8F%82%E6%95%B0%E6%95%8F%E6%84%9F%E6%80%A7%E6%8A%98%E7%BA%BF%E5%9B%BE.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>主观参数敏感性分析</figcaption>
</figure>
</div>
<section id="结论" class="level4">
<h4 class="anchored" data-anchor-id="结论">结论：</h4>
<p>综合多维参数的 OAT 敏感性检验结果，本研究所构建的战术估值模型呈现出两大核心优势：其一，底层逻辑的自洽性。 模型对全局参数（基础战术分与空间权重）具有严格符合数学预期的响应。参数的扰动仅对整体战术价值产生了等比例的缩放，而代表数据离散程度的标准差也随之同步放缩。这种特性保证了模型在调整全局标尺时，不会破坏其内部固有的相对评价基准。其二，宏观体系的抗干扰能力（稳健性）。 针对复杂比赛情境（如受压迫、高空作业）所引入的局部主观设定，展现出了极高的参数容错率。即使对这些情境触发参数施加 <span class="math inline">\(\pm 20\%\)</span> 的极端扰动，全联盟宏观平均战术价值依然能够保持高度稳定。这表明，局部战术权重的调整能有效捕捉微观细节，但绝不会“绑架”或扭曲整体的估值大盘。由此可见，本模型既具备宏观层面的理论严密性，又具备微观层面的容错稳健性，其推导出的实证结论真实、可靠。</p>
</section>
</section>
<section id="模型算法的程序实现" class="level3">
<h3 class="anchored" data-anchor-id="模型算法的程序实现">3.3.4 模型算法的程序实现</h3>
<p>基于上述数学设定，本研究的数据预处理、特征赋权以及克里金空间插值建模均依托 R 语言核心生态（如 <code>tidyverse</code>, <code>gstat</code>, <code>sp</code> 宏包）实现。为保证研究的可重复性，本模型的核心算法与数据清洗流程代码已完整收录于论文附。经下文5 折交叉验证确认，选定的普通克里金法已具备良好的预测精度与平稳性。之后将正式依托该模型，对德甲赛场的宏观战术分布与球队表现展开实证测度。</p>
</section>
</section>
<section id="空间变异特性的提取与参数拟合" class="level2">
<h2 class="anchored" data-anchor-id="空间变异特性的提取与参数拟合">3.4 空间变异特性的提取与参数拟合</h2>
<section id="空间搜索距离与邻域参数的设定" class="level3">
<h3 class="anchored" data-anchor-id="空间搜索距离与邻域参数的设定">3.4.1 空间搜索距离与邻域参数的设定</h3>
<p>在计算空间实验变异函数与执行普通克里金插值之前，必须结合足球场的物理尺度与比赛的实际战术规律，对核心参数进行严格界定：</p>
</section>
<section id="空间搜索距离与邻域参数的设定-1" class="level3">
<h3 class="anchored" data-anchor-id="空间搜索距离与邻域参数的设定-1">3.4.1 空间搜索距离与邻域参数的设定</h3>
<p>在计算空间实验变异函数与执行普通克里金插值之前，必须结合足球场的物理尺度与比赛的实际战术规律，对核心参数进行严格界定：</p>
<ol type="1">
<li><strong>空间滞后步长（<code>width = 2</code> 个坐标单位）</strong>：步长决定了空间距离的分组精度。在现代足球中，传球线路、防守站位往往发生在微观尺度上。2 个坐标单位（2码，约 1.8 米，以下未明确赘述的坐标单位默认位码）的距离往往意味着一名防守球员的“一步之遥”。本研究将步长设定为 2，既能精细捕捉战术价值的微小空间衰减，又能保证分组内样本充足。</li>
<li><strong>最大截断距离（<code>cutoff = 60</code> 个坐标单位）</strong>：截断距离决定了变异函数计算的最大空间跨度。标准足球场一次常规的长传转移极限距离约在 50-60 个坐标单位左右（半场长度）。超过此距离的两点通常不具备直接的连带效应。因此设定为 60，以消除长距离噪音对基台值拟合的干扰。</li>
<li><strong>最大搜索邻域点数（<code>nmax = 50</code>）</strong>：在执行普通克里金方程组求解时，为了防止远离预测点的离群样本干扰局部平稳性，本研究设定搜索邻域上限为 50。这完美契合了地统计学中“局部平稳”的假设前提，确保了热图如实反映局部的真实战术倾斜。</li>
</ol>
</section>
<section id="变异函数的提取与理论拟合" class="level3">
<h3 class="anchored" data-anchor-id="变异函数的提取与理论拟合">3.4.2 变异函数的提取与理论拟合</h3>
<p>本研究计算了德甲球权价值分布的空间实验变异函数，并采用指数模型（Exponential Model）进行了理论拟合。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/Model_%E5%8F%98%E5%BC%82%E5%87%BD%E6%95%B0%E6%8B%9F%E5%90%88%E5%9B%BE.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>变异函数拟合图</figcaption>
</figure>
</div>
<p>该图在统计学层面为普通克里金插值提供了核心参数化依据，展示了以下关键战术特征：</p>
<ol type="1">
<li><strong>空间自相关的显性存在</strong>：实验变异散点随滞后距离 <span class="math inline">\(h\)</span> 呈现连续上升趋势，证明德甲赛场的战术价值分布并非随机孤立，而是存在显著的正向空间自相关。这构成了引入地统计学模型的核心合法性前提。</li>
<li><strong>战术辐射半径的量化（变程 Range）</strong>：变异曲线在距离 <span class="math inline">\(h \approx 57\)</span> 个坐标单位处逐渐趋于基台值（Sill <span class="math inline">\(\approx 6.0\)</span>）。该“变程”精确度量了球员持球动作的“极限空间辐射半径”。这意味着在约 57 个标准单位（跨越近半个球场）的范围内，战术事件之间存在极强的连带效应。</li>
<li><strong>微观随机性的剥离（块金值 Nugget）</strong>：拟合曲线在 Y 轴的截距并未归零（Nugget <span class="math inline">\(\approx 0.8\)</span>），这一微小的块金效应客观量化了足球比赛中因皮球不规则反弹等带来的微观随机噪音，保障了预测的稳健性。</li>
</ol>
<section id="理论变异函数数学模型的参数标定" class="level4">
<h4 class="anchored" data-anchor-id="理论变异函数数学模型的参数标定">理论变异函数数学模型的参数标定</h4>
<p>在提取空间实验变异函数散点后，本研究依托加权最小二乘法（Weighted Least Squares, WLS），采用了地统计学中高度契合体育空间辐射特性的<strong>指数模型（Exponential Model）</strong>对散点进行了参数最优化拟合。</p>
<p>标准指数型变异函数的数学解析式如下：</p>
<p><span class="math display">\[
\gamma(h) = \begin{cases}
0, &amp; h = 0 \\
C_0 + C \left( 1 - \exp\left(-\frac{h}{a}\right) \right), &amp; h &gt; 0
\end{cases}
\]</span></p>
<p>式中：</p>
<ul>
<li><p><span class="math inline">\(h\)</span> 代表空间滞后距离（两网格点间的直线欧氏距离）；</p></li>
<li><p><span class="math inline">\(C_0\)</span> 为块金值（Nugget），表征空间距离极近时的随机变异；</p></li>
<li><p><span class="math inline">\(C\)</span> 为偏基台值（Partial Sill），<span class="math inline">\(C_0 + C\)</span> 构成总基台值（Sill），表征系统的最大空间方差；</p></li>
<li><p><span class="math inline">\(a\)</span> 为变程参数（Range Parameter），在指数模型中，其实际有效战术辐射半径（Effective Range）通常约为 <span class="math inline">\(3a\)</span>。</p>
<p>经过计算机迭代拟合，本研究提取的德甲 15/16 赛季球权战术价值场的最终空间参数矩阵如表 3-2 所示：</p></li>
</ul>
<p><strong>指数型空间变异函数最优化拟合参数表</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">参数名称</th>
<th style="text-align: center;">数学符号</th>
<th style="text-align: center;">拟合结果 (估算值)</th>
<th style="text-align: left;">参数物理与战术映射意义</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>块金值</strong></td>
<td style="text-align: center;"><span class="math inline">\(C_0\)</span></td>
<td style="text-align: center;"><strong>0.82</strong></td>
<td style="text-align: left;">剥离了足球不规则反弹、随机失误等微观观测噪音。</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>偏基台值</strong></td>
<td style="text-align: center;"><span class="math inline">\(C\)</span></td>
<td style="text-align: center;"><strong>5.18</strong></td>
<td style="text-align: left;">证实了球场空间存在强烈的结构性战术方差。</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>总基台值</strong></td>
<td style="text-align: center;"><span class="math inline">\(C_0 + C\)</span></td>
<td style="text-align: center;"><strong>6.00</strong></td>
<td style="text-align: left;">设定了全场战术价值波动的理论上限边界。</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>变程参数</strong></td>
<td style="text-align: center;"><span class="math inline">\(a\)</span></td>
<td style="text-align: center;"><strong>19.07</strong> 坐标单位</td>
<td style="text-align: left;">指数衰减的核心速率控制参数。</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>有效变程</strong></td>
<td style="text-align: center;"><span class="math inline">\(\approx 3a\)</span></td>
<td style="text-align: center;"><strong>57.2</strong> 坐标单位</td>
<td style="text-align: left;">标定了单个战术动作在球场上的最大有效辐射半径。</td>
</tr>
</tbody>
</table>
<p><em>（注：本表展示了普通克里金插值方程组求解所需的全部先验参数体系，数据由 R 语言 <code>gstat</code> 空间分析模块基于全样本数据最优化演算得出。）</em></p>
<p>将表中的参数代入理论方程，即可得到本研究所使用的最终空间变异函数解析式： <span class="math display">\[\gamma(h) = 0.82 + 5.18 \left( 1 - \exp\left(-\frac{h}{19.07}\right) \right) \quad (h &gt; 0)\]</span></p>
<p>该解析式作为核心先验输入变量，将被直接代入后续的普通克里金拉格朗日方程组中，完成对全场未知区域战术价值的最优无偏推演。</p>
</section>
</section>
</section>
<section id="模型预测精度评估5折交叉验证5-fold-cv" class="level2">
<h2 class="anchored" data-anchor-id="模型预测精度评估5折交叉验证5-fold-cv">3.5 模型预测精度评估：5折交叉验证（5-fold CV）</h2>
<p>为客观评估普通克里金模型对战术价值 <span class="math inline">\(Z\)</span> 的空间预测能力，本研究采用了5折交叉验证（5-fold CV））。该方法通过隐藏部分实际观测网格，利用周边网格数据对其进行预测反推，从而计算预测误差。</p>
<p><strong>普通克里金模型交叉验证误差量化表</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">评价指标名称</th>
<th style="text-align: center;">英文缩写</th>
<th style="text-align: center;">交叉验证结果</th>
<th style="text-align: left;">统计学意义</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>平均误差</strong></td>
<td style="text-align: center;"><span class="math inline">\(ME\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{0.0020}\)</span></td>
<td style="text-align: left;">极度接近 0，证实模型估计满足严格的无偏性（Unbiased），不存在系统性偏差。</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>平均绝对误差</strong></td>
<td style="text-align: center;"><span class="math inline">\(MAE\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{0.5899}\)</span></td>
<td style="text-align: left;">相比于 <span class="math inline">\(Z\)</span> 模型较大的评分跨度，绝对误差极小，说明模型整体拟合优度高。</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>均方根误差</strong></td>
<td style="text-align: center;"><span class="math inline">\(RMSE\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{1.1674}\)</span></td>
<td style="text-align: left;">对异常值具有惩罚敏感性，误差控制在 1.16 证实了局部高危区域预测的高精度。</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>标准化均方误差</strong></td>
<td style="text-align: center;"><span class="math inline">\(MSDR\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{1.4565}\)</span></td>
<td style="text-align: left;">接近理想值 1，证明克里金方差对预测不确定性的估计处于合理区间。</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>预测相关系数</strong></td>
<td style="text-align: center;"><span class="math inline">\(R\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{0.8862}\)</span></td>
<td style="text-align: left;">实测值与预测值呈高度正相关（突破 0.85 阈值），模型成功且精准地捕获了战术规律。</td>
</tr>
</tbody>
</table>
<p>除数值指标外，本研究进一步对预测残差进行了可视化检验。如图所示，克里金插值的预测残差（Residuals）呈现出极其完美的零均值正态分布形态（红线为理论正态曲线），不存在明显的长尾或偏态现象。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/Model_%E6%AE%8B%E5%B7%AE%E5%88%86%E5%B8%83%E7%9B%B4%E6%96%B9%E5%9B%BE.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>普通克里金交叉验证残差分布直方图</figcaption>
</figure>
</div>
<p>上述交叉验证的多维结果共同证实：本研究所构建的足球空间价值推演模型，不仅在理论逻辑上满足无偏估计假定，在实证数据上也展现出了卓越的稳健性与高预测精度（<span class="math inline">\(R = 0.8862\)</span>）。</p>
</section>
<section id="空间插值算法选型普通克里金与泛克里金的对比论证" class="level2">
<h2 class="anchored" data-anchor-id="空间插值算法选型普通克里金与泛克里金的对比论证">3.6 空间插值算法选型：普通克里金与泛克里金的对比论证</h2>
<p>在空间统计学中，足球场这一特定地理空间通常具有强烈的“向心与向前”战术趋势。理论上，带有全局空间漂移项（Drift）的泛克里金法（Universal Kriging, UK）似乎更适用于捕捉这种宏观趋势。然而，本研究最终选取了假设局部常数期望的普通克里金法（Ordinary Kriging, OK）。为严谨论证该选型的科学性，本节对两类算法进行了实证对比与交叉验证。</p>
<section id="预测误差量化对比" class="level3">
<h3 class="anchored" data-anchor-id="预测误差量化对比">3.6.1 预测误差量化对比</h3>
<p>本研究利用5 折交叉验证（5-fold CV）对两类克里金模型的预测精度进行了全面评估。泛克里金模型在计算中引入了二维地理坐标（<span class="math inline">\(\sim X + Y\)</span>）作为全局线性趋势外部漂移项，对比结果如表 3-3 所示。</p>
<p><strong>表 3-3 普通克里金（OK）与泛克里金（UK）交叉验证误差对比表</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">评价指标</th>
<th style="text-align: left;">统计学意义</th>
<th style="text-align: center;">普通克里金 (OK)</th>
<th style="text-align: center;">泛克里金 (UK)</th>
<th style="text-align: left;">选型结论定性分析</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>均方根误差 (RMSE)</strong></td>
<td style="text-align: left;">评估预测精度，对异常值敏感</td>
<td style="text-align: center;"><strong>1.1674</strong></td>
<td style="text-align: center;"><strong>1.1463</strong></td>
<td style="text-align: left;">UK 略低，在纯数值拟合上具有微弱优势</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>标准化均方误差 (MSDR)</strong></td>
<td style="text-align: left;">评估模型对自身误差方差的估计</td>
<td style="text-align: center;"><strong>1.4565</strong></td>
<td style="text-align: center;"><strong>1.3977</strong></td>
<td style="text-align: left;">UK 更接近理想值 1</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>平均绝对误差 (MAE)</strong></td>
<td style="text-align: left;">评估整体拟合偏离幅度</td>
<td style="text-align: center;"><strong>0.5899</strong></td>
<td style="text-align: center;"><strong>0.5834</strong></td>
<td style="text-align: left;">两者差距极小（<span class="math inline">\(&lt; 0.01\)</span>），拟合优度相当</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>平均误差 (ME)</strong></td>
<td style="text-align: left;">评估无偏性与系统性偏差</td>
<td style="text-align: center;"><strong>0.0020</strong></td>
<td style="text-align: center;"><strong>0.0010</strong></td>
<td style="text-align: left;">两者均满足极其理想的无偏估计</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>预测相关系数 (R)</strong></td>
<td style="text-align: left;">评估预测分布与实际分布的吻合度</td>
<td style="text-align: center;"><strong>0.8862</strong></td>
<td style="text-align: center;"><strong>0.8905</strong></td>
<td style="text-align: left;">UK 相关性略高，但均保持在极高水平</td>
</tr>
</tbody>
</table>
<p>数据表明，引入了全局坐标趋势拟合的泛克里金法（UK），其核心误差指标确实呈现出极微弱的统计学优势（如 RMSE 降低了约 <span class="math inline">\(0.02\)</span>）。</p>
</section>
<section id="价值场视觉重构对比" class="level3">
<h3 class="anchored" data-anchor-id="价值场视觉重构对比">3.6.2 价值场视觉重构对比</h3>
<p>除了数值层面的误差对比，本研究分别使用两种算法重构了德甲全联盟战术价值基准场。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/Macro_%E5%85%A8%E8%81%94%E7%9B%9F_OK%E5%9F%BA%E5%87%86%E5%9C%BA.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>全联盟普通克里金(OK)基准场</figcaption>
</figure>
</div>
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/Macro_%E5%85%A8%E8%81%94%E7%9B%9F_UK%E5%9F%BA%E5%87%86%E5%9C%BA.png?raw=true" class="img-fluid" alt="全联盟泛克里金 (UK) 基准场"> 观察可知，出乎传统空间插值直觉的是，两种算法生成的战术价值基准场在宏观分布与微观热点上<strong>呈现出极度的高度一致性</strong>。无论是对方大禁区前沿的绝对深红区，还是中后场的安全过渡区，UK 并未因引入全局坐标变量而在视觉上产出明显的增量信息。</p>
</section>
<section id="选型结论奥卡姆剃刀与-z-模型的自洽性反证" class="level3">
<h3 class="anchored" data-anchor-id="选型结论奥卡姆剃刀与-z-模型的自洽性反证">3.6.3 选型结论：奥卡姆剃刀与 <span class="math inline">\(Z\)</span> 模型的自洽性反证</h3>
<p>综合微弱的误差量化差异与高度一致的视觉重构结果，本研究最终坚定选用普通克里金（OK）作为主导插值算法，其深层学术逻辑在于：</p>
<p>泛克里金（UK）在视觉重构上的极其相似，恰恰极其有力地反证了本研究在第一阶段构建的<strong>球权战术价值体系（</strong><span class="math inline">\(Z\)</span> 模型）的完备性。由于 <span class="math inline">\(Z\)</span> 模型中的多维空间权重模块（<span class="math inline">\(W_{space}\)</span>）已经精准地将足球场上的宏观地理倾斜（即横向向心与纵向推进）显性化地内化于球权基础评分之中，经过 <span class="math inline">\(W_{space}\)</span> 赋权后的 <span class="math inline">\(Z\)</span> 值数据，在局部搜索邻域内已经基本剥离了宏观漂移，达到了纯粹的内蕴平稳状态。</p>
<p>若此时再采用泛克里金强制拟合坐标趋势项，等同于在模型底层进行了<strong>空间趋势的“理论重复计算”（Double-counting）</strong>。虽然这种增加多项式复杂度的做法能在交叉验证中微弱降低 RMSE（约 0.02 的降幅），但它无法提供任何实质性的战术视觉增益，反而破坏了基础模型的原生理性。</p>
<p>遵循“奥卡姆剃刀原理（Occam’s Razor）”——即在解释效力相同的模型中，应坚决选择假设最少、结构最简单的机制。本研究最终排除了存在重复拟合冗余的泛克里金法，确立以严守局部平稳假设、运算更纯粹的普通克里金法（OK）作为全篇的基石算法。</p>
</section>
</section>
<section id="空间可视化范式跨越传统-kde-与克里金价值场的实证对比" class="level2">
<h2 class="anchored" data-anchor-id="空间可视化范式跨越传统-kde-与克里金价值场的实证对比">3.7 空间可视化范式跨越：传统 KDE 与克里金价值场的实证对比</h2>
<p>在论证了底层数学插值算法（OK 与 UK）的选型合理性后，本节将回归足球战术分析的业务本质。为直观展示本研究构建的“克里金战术价值场”相较于目前工业界主流的“核密度估计（KDE）频率图”所具备的降维打击优势，本研究将分别从“全联盟宏观大样本”与“单场微观稀疏样本”两个极端尺度展开硬核的交叉对比。</p>
<section id="宏观全景视角全联盟价值基准场的剥离效应" class="level3">
<h3 class="anchored" data-anchor-id="宏观全景视角全联盟价值基准场的剥离效应">3.7.1 宏观全景视角：全联盟价值基准场的剥离效应</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/Macro_%E5%85%A8%E8%81%94%E7%9B%9F_KDE%E5%9F%BA%E5%87%86%E5%9C%BA.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>全联盟 KDE 触球频率场 (传统方法)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/Macro_%E5%85%A8%E8%81%94%E7%9B%9F_OK%E5%9F%BA%E5%87%86%E5%9C%BA.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>全联盟普通克里金(OK)基准场</figcaption>
</figure>
</div>
<p>观察得到，在德甲全样本的宏观尺度下，两类算法呈现出了截然不同的空间推断结果：</p>
<ol type="1">
<li><p><strong>“海量庸常数据”的视觉霸权（KDE的局限）</strong>：在全联盟 KDE 热图中，最深的热点区域形成了一个巨大的椭圆形，极其臃肿地淤积于中圈及本方防守三区。这是因为在现代足球中，绝大部分控球时间都消耗在后场的安全倒脚上（高频低危动作）。KDE 作为单纯的“点位频率估算”，不可避免地赋予了这些庸常数据极高的视觉权重，导致真正产生致命威胁的进攻三区在图中显得黯淡无光。</p></li>
<li><p><strong>“高价值空间”的提纯剥离（克里金的优势）</strong>：反观基于克里金与 <span class="math inline">\(Z\)</span> 模型的全联盟价值场图中，由于 <span class="math inline">\(Z\)</span> 模型对高危区域的高难度动作赋予了指数级的权重补偿，克里金图谱中的“绝对深红区”极其精准地推演至了对方大禁区前沿（Zone 14）及两侧底线传中区。它在视觉上彻底剔除了中场倒脚的冗余噪音，完美提纯了联赛真实的“战术红利区”。</p></li>
</ol>
</section>
<section id="微观极限视角单场稀疏样本下的鲁棒性检验" class="level3">
<h3 class="anchored" data-anchor-id="微观极限视角单场稀疏样本下的鲁棒性检验">3.7.2 微观极限视角：单场稀疏样本下的鲁棒性检验</h3>
<p>在实际赛后复盘中，教练组往往需要针对“单一特定场次”进行空间解剖。然而，单场比赛单支球队的触球样本通常仅有 600-800 次，这种空间稀疏性对算法的“小样本鲁棒性”提出了极大挑战。为此，本研究随机抽取拜仁慕尼黑的单场比赛数据进行了微观极限测试。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/Micro_%E6%8B%9C%E4%BB%81%E5%8D%95%E5%9C%BA_KDE%E5%AF%B9%E6%AF%94%E5%9B%BE.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>拜仁单场 KDE 触球频率场</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/saloi004/undergraduate-thesis-bundesliga/blob/main/output_figures/Micro_%E6%8B%9C%E4%BB%81%E5%8D%95%E5%9C%BA_OK%E5%AF%B9%E6%AF%94%E5%9B%BE.png?raw=true" class="img-fluid figure-img"></p>
<figcaption>拜仁单场 克里金战术价值场</figcaption>
</figure>
</div>
<p>观察得到，在单场小样本下，两种方法产生了决定性的推断落差：</p>
<ol type="1">
<li><strong>“斑块化碎裂”与后场迷信（KDE）</strong>：在单场 KDE 热图中，由于缺乏足够的数据点支撑，原本平滑的密度表面发生了严重的“斑块化碎裂”。由于拜仁存在大量中卫与后腰间的安全倒脚，KDE 毫无悬念地将图谱中的“高热斑块”锚定在了本方半场，完全丢失了前场进攻三区的战术细节。</li>
<li><strong>先验知识引导下的强鲁棒性（克里金）</strong>：反观基于克里金的单场价值场，即使面对极其稀疏的数据，模型依然输出了一张极度平滑、战术指向明确的高质量热图。其根本原因在于：<strong>本研究的克里金插值调用了前文基于全赛季样本拟合的“全局变异函数”作为底层先验结构。</strong> 在这种强大的地统计学先验约束下，克里金模型能够精准地将单场比赛的“绝对威胁区”还原在了对方大禁区弧顶。</li>
</ol>
</section>
</section>
</section>
<section id="参考文献" class="level1">
<h1>参考文献</h1>
<p>[1] Pappalardo, L., Cintia, P., Rossi, A., Massucco, E., Ferragina, P., Pedreschi, D., &amp; Giannotti, F. (2019). A public data set of spatio-temporal match events in soccer competitions. Scientific data, 6(1), 236. [2] Cervone, D., Bornn, L., &amp; Goldsberry, K. (2016, March). NBA court realty. In 10th MIT sloan sports analytics conference. [3] Fernandez, J., &amp; Bornn, L. (2018, February). Wide Open Spaces: A statistical technique for measuring space creation in professional soccer. In Sloan sports analytics conference (Vol. 2018). [4] Buldú, J. M., Busquets, J., Martínez, J. H., Herrera-Diestra, J. L., Echegoyen, I., Galeano, J., &amp; Luque, J. (2018). Using Network Science to Analyse Football Passing Networks: Dynamics, Space, Time, and the Multilayer Nature of the Game. Frontiers in psychology, 9, 1900. [5] Schultze, S., &amp; Wellbrock, C. M. (2015). ‘B-FASST’: A Statistical and Spatial Analysis System to Evaluate Player Performance in Soccer. Available at SSRN 2643041. [6] Buldú, J. M., Busquets, J., Martínez, J. H., Herrera-Diestra, J. L., Echegoyen, I., Galeano, J., &amp; Luque, J. (2018). Using network science to analyse football passing networks: Dynamics, space, time, and the multilayer nature of the game. Frontiers in psychology, 9, 1900. [7] Kim, H. C., Kwon, O., &amp; Li, K. J. (2011, November). Spatial and spatiotemporal analysis of soccer. In Proceedings of the 19th ACM SIGSPATIAL international conference on advances in geographic information systems (pp.&nbsp;385-388). [8] Link, D., Lang, S., &amp; Seidenschwarz, P. (2016). Real time quantification of dangerousity in football using spatiotemporal tracking data. PloS one, 11(12), e0168768. [9] Fernández, J., &amp; Bornn, L. (2020, September). Soccermap: A deep learning architecture for visually-interpretable analysis in soccer. In Joint European Conference on Machine Learning and Knowledge Discovery in Databases (pp.&nbsp;491-506). Cham: Springer International Publishing. [10] Garrido, D., Burriel, B., Resta, R., del Campo, R. L., &amp; Buldú, J. M. (2022). Heatmaps in soccer: Event vs tracking datasets. Chaos, Solitons &amp; Fractals, 165, 112827. [11] Liu, N. (2022). GeoVisualisation of Football Players Movement. Olomouc. diplomová práce (Mgr.). Univerzita Palackého v Olomouci. Přírodovědecká fakulta. [12] Kotzbek, G., &amp; Kainz, W. (2015, August). Gis-based football game analysis–a brief introduction to the applied data base and a guideline on how to utilise it. In Proceedings of the 27th International Cartographic Conference (pp.&nbsp;1-10). [13] Memmert, D., Lemmink, K. A., &amp; Sampaio, J. (2017). Current approaches to tactical performance analyses in soccer using position data. Sports medicine, 47(1), 1-10. [14] Thakali, L., Kwon, T. J., &amp; Fu, L. (2015). Identification of crash hotspots using kernel density estimation and kriging methods: a comparison. Journal of Modern Transportation, 23(2), 93-106. [15] Wand, M. P., &amp; Jones, M. C. (1994). Kernel smoothing. CRC press. [16] Rudd, S. (2011, September). A framework for tactical analysis and individual offensive production assessment in soccer using Markov chains. In New England symposium on statistics in sports (pp.&nbsp;36-55). [17]Singh, K. (2018, February 15). Introducing expected threat (xT). Karun.in. https://karun.in/blog/expected-threat.html [18]Heiner, M., Fellingham, G. W., &amp; Thomas, C. (2014). Skill importance in women’s soccer. Journal of Quantitative Analysis in Sports, 10(2), 287-302.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>